
var ProtocolMgr = function() {
    function t() {
        this._pkgMap = new PkgMap,
            this.InitPkgMap()
    }
    var e = (__define, t),
        a = e.prototype;
    return a.GetPkgMap = function() {
            return this._pkgMap
        },
        a.InitPkgMap = function() {
            this._pkgMap.AddPkg(t.ID_DceAccBind, "DceAccBind"),
                this._pkgMap.AddPkg(t.ID_DceActivity, "DceActivity"),
                this._pkgMap.AddPkg(t.ID_DceActivityData, "DceActivityData"),
                this._pkgMap.AddPkg(t.ID_DceAddFriend, "DceAddFriend"),
                this._pkgMap.AddPkg(t.ID_DceAllLastID, "DceAllLastID"),
                this._pkgMap.AddPkg(t.ID_DceApplyList, "DceApplyList"),
                this._pkgMap.AddPkg(t.ID_DceArenaExchange, "DceArenaExchange"),
                this._pkgMap.AddPkg(t.ID_DceAutoEquipSoldier, "DceAutoEquipSoldier"),
                this._pkgMap.AddPkg(t.ID_DceAwardCenter, "DceAwardCenter"),
                this._pkgMap.AddPkg(t.ID_DceBattleReview, "DceBattleReview"),
                this._pkgMap.AddPkg(t.ID_DceBattleStart, "DceBattleStart"),
                this._pkgMap.AddPkg(t.ID_DceBlackList, "DceBlackList"),
                this._pkgMap.AddPkg(t.ID_DceBlackListOpt, "DceBlackListOpt"),
                this._pkgMap.AddPkg(t.ID_DceBuy, "DceBuy"),
                this._pkgMap.AddPkg(t.ID_DceBuyGuard, "DceBuyGuard"),
                this._pkgMap.AddPkg(t.ID_DceBuyOil, "DceBuyOil"),
                this._pkgMap.AddPkg(t.ID_DceCampBattleData, "DceCampBattleData"),
                this._pkgMap.AddPkg(t.ID_DceCampBattleMove, "DceCampBattleMove"),
                this._pkgMap.AddPkg(t.ID_DceCampBattleResult, "DceCampBattleResult"),
                this._pkgMap.AddPkg(t.ID_DceCenterRecovery, "DceCenterRecovery"),
                this._pkgMap.AddPkg(t.ID_DceChargePaper, "DceChargePaper"),
                this._pkgMap.AddPkg(t.ID_DceChat, "DceChat"),
                this._pkgMap.AddPkg(t.ID_DceChatData, "DceChatData"),
                this._pkgMap.AddPkg(t.ID_DceCheckPlayerName, "DceCheckPlayerName"),
                this._pkgMap.AddPkg(t.ID_DceChristmasMineral, "DceChristmasMineral"),
                this._pkgMap.AddPkg(t.ID_DceChristmasMineralStart, "DceChristmasMineralStart"),
                this._pkgMap.AddPkg(t.ID_DceChristmasScroeExchange, "DceChristmasScroeExchange"),
                this._pkgMap.AddPkg(t.ID_DceChritmasLottery, "DceChritmasLottery"),
                this._pkgMap.AddPkg(t.ID_DceChritmasLotteryStart, "DceChritmasLotteryStart"),
                this._pkgMap.AddPkg(t.ID_DceClearCampBattleCD, "DceClearCampBattleCD"),
                this._pkgMap.AddPkg(t.ID_DceComposeParts, "DceComposeParts"),
                this._pkgMap.AddPkg(t.ID_DceConsumeExchange, "DceConsumeExchange"),
                this._pkgMap.AddPkg(t.ID_DceConsumeExchangeData, "DceConsumeExchangeData"),
                this._pkgMap.AddPkg(t.ID_DceCreateGuild, "DceCreateGuild"),
                this._pkgMap.AddPkg(t.ID_DceCreateShip, "DceCreateShip"),
                this._pkgMap.AddPkg(t.ID_DceDayLimitFightData, "DceDayLimitFightData"),
                this._pkgMap.AddPkg(t.ID_DceDecomposeParts, "DceDecomposeParts"),
                this._pkgMap.AddPkg(t.ID_DceDeleteFriend, "DceDeleteFriend"),
                this._pkgMap.AddPkg(t.ID_DceDrawAllElectric, "DceDrawAllElectric"),
                this._pkgMap.AddPkg(t.ID_DceDrawElectric, "DceDrawElectric"),
                this._pkgMap.AddPkg(t.ID_DceEnterArena, "DceEnterArena"),
                this._pkgMap.AddPkg(t.ID_DceEnterCampBattle, "DceEnterCampBattle"),
                this._pkgMap.AddPkg(t.ID_DceEnterGuard, "DceEnterGuard"),
                this._pkgMap.AddPkg(t.ID_DceEquipParts, "DceEquipParts"),
                this._pkgMap.AddPkg(t.ID_DceEquipSoul, "DceEquipSoul"),
                this._pkgMap.AddPkg(t.ID_DceFriendList, "DceFriendList"),
                this._pkgMap.AddPkg(t.ID_DceGetAward, "DceGetAward"),
                this._pkgMap.AddPkg(t.ID_DceGetCenterGold, "DceGetCenterGold"),
                this._pkgMap.AddPkg(t.ID_DceGetDayLimitFight, "DceGetDayLimitFight"),
                this._pkgMap.AddPkg(t.ID_DceGetGuardRank, "DceGetGuardRank"),
                this._pkgMap.AddPkg(t.ID_DceGetMailProp, "DceGetMailProp"),
                this._pkgMap.AddPkg(t.ID_DceGetMedal, "DceGetMedal"),
                this._pkgMap.AddPkg(t.ID_DceGetTactic, "DceGetTactic"),
                this._pkgMap.AddPkg(t.ID_DceGetWeakCamp, "DceGetWeakCamp"),
                this._pkgMap.AddPkg(t.ID_DceGhostShip, "DceGhostShip"),
                this._pkgMap.AddPkg(t.ID_DceGhostShipData, "DceGhostShipData"),
                this._pkgMap.AddPkg(t.ID_DceGuardStage, "DceGuardStage"),
                this._pkgMap.AddPkg(t.ID_DceGuideStep, "DceGuideStep"),
                this._pkgMap.AddPkg(t.ID_DceGuildApply, "DceGuildApply"),
                this._pkgMap.AddPkg(t.ID_DceGuildApplyList, "DceGuildApplyList"),
                this._pkgMap.AddPkg(t.ID_DceGuildApproval, "DceGuildApproval"),
                this._pkgMap.AddPkg(t.ID_DceGuildBuyGift, "DceGuildBuyGift"),
                this._pkgMap.AddPkg(t.ID_DceGuildCancelApply, "DceGuildCancelApply"),
                this._pkgMap.AddPkg(t.ID_DceGuildData, "DceGuildData"),
                this._pkgMap.AddPkg(t.ID_DceGuildDemise, "DceGuildDemise"),
                this._pkgMap.AddPkg(t.ID_DceGuildDismiss, "DceGuildDismiss"),
                this._pkgMap.AddPkg(t.ID_DceGuildDismissCancel, "DceGuildDismissCancel"),
                this._pkgMap.AddPkg(t.ID_DceGuildDonate, "DceGuildDonate"),
                this._pkgMap.AddPkg(t.ID_DceGuildExpel, "DceGuildExpel"),
                this._pkgMap.AddPkg(t.ID_DceGuildFireDeputy, "DceGuildFireDeputy"),
                this._pkgMap.AddPkg(t.ID_DceGuildInvite, "DceGuildInvite"),
                this._pkgMap.AddPkg(t.ID_DceGuildList, "DceGuildList"),
                this._pkgMap.AddPkg(t.ID_DceGuildMemberList, "DceGuildMemberList"),
                this._pkgMap.AddPkg(t.ID_DceGuildQuit, "DceGuildQuit"),
                this._pkgMap.AddPkg(t.ID_DceGuildSetDeputy, "DceGuildSetDeputy"),
                this._pkgMap.AddPkg(t.ID_DceGuildSetMedal, "DceGuildSetMedal"),
                this._pkgMap.AddPkg(t.ID_DceGuildUpgrade, "DceGuildUpgrade"),
                this._pkgMap.AddPkg(t.ID_DceHeartbeat, "DceHeartbeat"),
                this._pkgMap.AddPkg(t.ID_DceInvitedList, "DceInvitedList"),
                this._pkgMap.AddPkg(t.ID_DceInviteFriend, "DceInviteFriend"),
                this._pkgMap.AddPkg(t.ID_DceLimitShip, "DceLimitShip"),
                this._pkgMap.AddPkg(t.ID_DceLimitShipData, "DceLimitShipData"),
                this._pkgMap.AddPkg(t.ID_DceLuckyGoddessData, "DceLuckyGoddessData"),
                this._pkgMap.AddPkg(t.ID_DceLuckyGoddessForFree, "DceLuckyGoddessForFree"),
                this._pkgMap.AddPkg(t.ID_DceLuckyWheelActivity, "DceLuckyWheelActivity"),
                this._pkgMap.AddPkg(t.ID_DceLuckyWheelActivityData, "DceLuckyWheelActivityData"),
                this._pkgMap.AddPkg(t.ID_DceMailList, "DceMailList"),
                this._pkgMap.AddPkg(t.ID_DceMedalData, "DceMedalData"),
                this._pkgMap.AddPkg(t.ID_DceMilitaryRankGetDailyReward, "DceMilitaryRankGetDailyReward"),
                this._pkgMap.AddPkg(t.ID_DceMilitaryRankInfo, "DceMilitaryRankInfo"),
                this._pkgMap.AddPkg(t.ID_DceMilitaryRankUpgrad, "DceMilitaryRankUpgrad"),
                this._pkgMap.AddPkg(t.ID_DceMisteryShopRefresh, "DceMisteryShopRefresh"),
                this._pkgMap.AddPkg(t.ID_DceModifyDeclaration, "DceModifyDeclaration"),
                this._pkgMap.AddPkg(t.ID_DceModifyNotify, "DceModifyNotify"),
                this._pkgMap.AddPkg(t.ID_DceMonthCard, "DceMonthCard"),
                this._pkgMap.AddPkg(t.ID_DceMonthSignTake, "DceMonthSignTake"),
                this._pkgMap.AddPkg(t.ID_DceNewDay, "DceNewDay"),
                this._pkgMap.AddPkg(t.ID_DceOwnedPaper, "DceOwnedPaper"),
                this._pkgMap.AddPkg(t.ID_DcePaperChargeCount, "DcePaperChargeCount"),
                this._pkgMap.AddPkg(t.ID_DcePaperList, "DcePaperList"),
                this._pkgMap.AddPkg(t.ID_DcePaperPieceList, "DcePaperPieceList"),
                this._pkgMap.AddPkg(t.ID_DcePartPieceList, "DcePartPieceList"),
                this._pkgMap.AddPkg(t.ID_DcePartsList, "DcePartsList"),
                this._pkgMap.AddPkg(t.ID_DcePropList, "DcePropList"),
                this._pkgMap.AddPkg(t.ID_DceQuestionAnswer, "DceQuestionAnswer"),
                this._pkgMap.AddPkg(t.ID_DceQuestionList, "DceQuestionList"),
                this._pkgMap.AddPkg(t.ID_DceQuestionRank, "DceQuestionRank"),
                this._pkgMap.AddPkg(t.ID_DceRankList, "DceRankList"),
                this._pkgMap.AddPkg(t.ID_DceRecElectricList, "DceRecElectricList"),
                this._pkgMap.AddPkg(t.ID_DceRecommandInviteList, "DceRecommandInviteList"),
                this._pkgMap.AddPkg(t.ID_DceRefuseAddFriend, "DceRefuseAddFriend"),
                this._pkgMap.AddPkg(t.ID_DceRemouldParts, "DceRemouldParts"),
                this._pkgMap.AddPkg(t.ID_DceRemouldShip, "DceRemouldShip"),
                this._pkgMap.AddPkg(t.ID_DceRenameRole, "DceRenameRole"),
                this._pkgMap.AddPkg(t.ID_DceRenameShip, "DceRenameShip"),
                this._pkgMap.AddPkg(t.ID_DceResetGuard, "DceResetGuard"),
                this._pkgMap.AddPkg(t.ID_DceResetStageCount, "DceResetStageCount"),
                this._pkgMap.AddPkg(t.ID_DceRetireShip, "DceRetireShip"),
                this._pkgMap.AddPkg(t.ID_DceRobberyList, "DceRobberyList"),
                this._pkgMap.AddPkg(t.ID_DceSalePaper, "DceSalePaper"),
                this._pkgMap.AddPkg(t.ID_DceSaveTrain, "DceSaveTrain"),
                this._pkgMap.AddPkg(t.ID_DceScienceList, "DceScienceList"),
                this._pkgMap.AddPkg(t.ID_DceScoutSoldier, "DceScoutSoldier"),
                this._pkgMap.AddPkg(t.ID_DceSearchGuild, "DceSearchGuild"),
                this._pkgMap.AddPkg(t.ID_DceSearchPlayer, "DceSearchPlayer"),
                this._pkgMap.AddPkg(t.ID_DceSellProp, "DceSellProp"),
                this._pkgMap.AddPkg(t.ID_DceSendElectric, "DceSendElectric"),
                this._pkgMap.AddPkg(t.ID_DceSendMail, "DceSendMail"),
                this._pkgMap.AddPkg(t.ID_DceSetCaption, "DceSetCaption"),
                this._pkgMap.AddPkg(t.ID_DceSetRole, "DceSetRole"),
                this._pkgMap.AddPkg(t.ID_DceSetSoldier, "DceSetSoldier"),
                this._pkgMap.AddPkg(t.ID_DceSetTactic, "DceSetTactic"),
                this._pkgMap.AddPkg(t.ID_DceSetVerifyOptions, "DceSetVerifyOptions"),
                this._pkgMap.AddPkg(t.ID_DceSevenDaysExchange, "DceSevenDaysExchange"),
                this._pkgMap.AddPkg(t.ID_DceSevenDaysExchangeData, "DceSevenDaysExchangeData"),
                this._pkgMap.AddPkg(t.ID_DceShipList, "DceShipList"),
                this._pkgMap.AddPkg(t.ID_DceShopData, "DceShopData"),
                this._pkgMap.AddPkg(t.ID_DceSoldierList, "DceSoldierList"),
                this._pkgMap.AddPkg(t.ID_DceSoul, "DceSoul"),
                this._pkgMap.AddPkg(t.ID_DceSoulEat, "DceSoulEat"),
                this._pkgMap.AddPkg(t.ID_DceSoulList, "DceSoulList"),
                this._pkgMap.AddPkg(t.ID_DceSpy, "DceSpy"),
                this._pkgMap.AddPkg(t.ID_DceSpyData, "DceSpyData"),
                this._pkgMap.AddPkg(t.ID_DceStageList, "DceStageList"),
                this._pkgMap.AddPkg(t.ID_DceTrain, "DceTrain"),
                this._pkgMap.AddPkg(t.ID_DceUnEquipParts, "DceUnEquipParts"),
                this._pkgMap.AddPkg(t.ID_DceUnEquipSoul, "DceUnEquipSoul"),
                this._pkgMap.AddPkg(t.ID_DceUpdateElectric, "DceUpdateElectric"),
                this._pkgMap.AddPkg(t.ID_DceUpdateOil, "DceUpdateOil"),
                this._pkgMap.AddPkg(t.ID_DceUpgradeBuild, "DceUpgradeBuild"),
                this._pkgMap.AddPkg(t.ID_DceUpgradeParts, "DceUpgradeParts"),
                this._pkgMap.AddPkg(t.ID_DceUpgradeScience, "DceUpgradeScience"),
                this._pkgMap.AddPkg(t.ID_DceUpgradeShip, "DceUpgradeShip"),
                this._pkgMap.AddPkg(t.ID_DceUpgradeSkill, "DceUpgradeSkill"),
                this._pkgMap.AddPkg(t.ID_DceUseProp, "DceUseProp"),
                this._pkgMap.AddPkg(t.ID_DceUserComeBackReward, "DceUserComeBackReward"),
                this._pkgMap.AddPkg(t.ID_DceUserData, "DceUserData"),
                this._pkgMap.AddPkg(t.ID_DceGoddessReward, "DceGoddessReward"),
                this._pkgMap.AddPkg(t.ID_DceGoddessRewardData, "DceGoddessRewardData"),
                this._pkgMap.AddPkg(t.ID_DceLuckyCatDataRequest, "DceLuckyCatDataRequest"),
                this._pkgMap.AddPkg(t.ID_DceLuckyCatRequest, "DceLuckyCatRequest"),
                this._pkgMap.AddPkg(t.ID_DceLuckBoxPointExchange, "DceLuckBoxPointExchange"),
                this._pkgMap.AddPkg(t.ID_DceLuckBoxPointExchangeOpen, "DceLuckBoxPointExchangeOpen"),
                this._pkgMap.AddPkg(t.ID_DceLoginPokerOpen, "DceLoginPokerOpen"),
                this._pkgMap.AddPkg(t.ID_DceLoginPokerAction, "DceLoginPokerAction"),
                this._pkgMap.AddPkg(t.ID_DceLoginPokerFinal, "DceLoginPokerFinal"),
                this._pkgMap.AddPkg(t.ID_DceReductionParts, "DceReductionParts"),
                this._pkgMap.AddPkg(t.ID_DceBonusFlyDataRequest, "DceBonusFlyDataRequest"),
                this._pkgMap.AddPkg(t.ID_DceBonusFlyRequest, "DceBonusFlyRequest"),
                this._pkgMap.AddPkg(t.ID_DceRechargeSevenDayRequest, "DceRechargeSevenDayRequest"),
                this._pkgMap.AddPkg(t.ID_DceRechargeSevenDayRequestData, "DceRechargeSevenDayRequestData"),
                this._pkgMap.AddPkg(t.ID_DceEnterCenterCampBattle, "DceEnterCenterCampBattle"),
                this._pkgMap.AddPkg(t.ID_DceCenterCampBattleData, "DceCenterCampBattleData"),
                this._pkgMap.AddPkg(t.ID_DceCenterCampBattleMove, "DceCenterCampBattleMove"),
                this._pkgMap.AddPkg(t.ID_DceCenterCampBattleResult, "DceCenterCampBattleResult"),
                this._pkgMap.AddPkg(t.ID_DceClearCenterCampBattleCD, "DceClearCenterCampBattleCD"),
                this._pkgMap.AddPkg(t.ID_DceCenterCampBattleRankList, "DceCenterCampBattleRankList"),
                this._pkgMap.AddPkg(t.ID_DceReductionPartsInfo, "DceReductionPartsInfo"),
                this._pkgMap.AddPkg(t.ID_DceUsePaperPieceGift, "DceUsePaperPieceGift"),
                this._pkgMap.AddPkg(t.ID_DceOnearmedBanditDataRequest, "DceOnearmedBanditDataRequest"),
                this._pkgMap.AddPkg(t.ID_DceOnearmedBanditRequest, "DceOnearmedBanditRequest"),
                this._pkgMap.AddPkg(t.ID_DceValentineDataRequest, "DceValentineDataRequest"),
                this._pkgMap.AddPkg(t.ID_DceValentineGiveGift, "DceValentineGiveGift"),
                this._pkgMap.AddPkg(t.ID_DceCampBattleBuy, "DceCampBattleBuy"),
                this._pkgMap.AddPkg(t.ID_DceCenterCampBattleBuy, "DceCenterCampBattleBuy"),
                this._pkgMap.AddPkg(t.ID_DceLuckyGoddnessForCharge, "DceLuckyGoddnessForCharge"),
                this._pkgMap.AddPkg(t.ID_DceShipFormationInfo, "DceShipFormationInfo"),
                this._pkgMap.AddPkg(t.ID_DceShipFormationLevelUp, "DceShipFormationLevelUp"),
                this._pkgMap.AddPkg(t.ID_DceShipFormationChoose, "DceShipFormationChoose"),
                this._pkgMap.AddPkg(t.ID_DceRegSecondDayGift, "DceRegSecondDayGift"),
                this._pkgMap.AddPkg(t.ID_DceBuySpyItem, "DceBuySpyItem"),
                this._pkgMap.AddPkg(t.ID_DceChallengeDataRequest, "DceChallengeDataRequest"),
                this._pkgMap.AddPkg(t.ID_DceChallengeSignUp, "DceChallengeSignUp"),
                this._pkgMap.AddPkg(t.ID_DceChallengeFight, "DceChallengeFight"),
                this._pkgMap.AddPkg(t.ID_DceChallengeAction, "DceChallengeAction"),
                this._pkgMap.AddPkg(t.ID_DceChallengeEnemyData, "DceChallengeEnemyData"),
                this._pkgMap.AddPkg(t.ID_DceChallengeRevenge, "DceChallengeRevenge"),
                this._pkgMap.AddPkg(t.ID_DceChallengeRefresh, "DceChallengeRefresh"),
                this._pkgMap.AddPkg(t.ID_DceChallengeRank, "DceChallengeRank"),
                this._pkgMap.AddPkg(t.ID_DceChallengeChampion, "DceChallengeChampion"),
                this._pkgMap.AddPkg(t.ID_DceChallengeWorship, "DceChallengeWorship"),
                this._pkgMap.AddPkg(t.ID_DceChallengeBuy, "DceChallengeBuy"),
                this._pkgMap.AddPkg(t.ID_DceChallengeRefreshCharge, "DceChallengeRefreshCharge"),
                this._pkgMap.AddPkg(t.ID_DceBuyRecruitItem, "DceBuyRecruitItem"),
                this._pkgMap.AddPkg(t.ID_DceCaptainData, "DceCaptainData"),
                this._pkgMap.AddPkg(t.ID_DceCaptainList, "DceCaptainList"),
                this._pkgMap.AddPkg(t.ID_DceCaptainPieceList, "DceCaptainPieceList"),
                this._pkgMap.AddPkg(t.ID_DceComposeCaptain, "DceComposeCaptain"),
                this._pkgMap.AddPkg(t.ID_DceEquipCaptain, "DceEquipCaptain"),
                this._pkgMap.AddPkg(t.ID_DceExchangeCaptain, "DceExchangeCaptain"),
                this._pkgMap.AddPkg(t.ID_DceFireCaptain, "DceFireCaptain"),
                this._pkgMap.AddPkg(t.ID_DceLimitCaptain, "DceLimitCaptain"),
                this._pkgMap.AddPkg(t.ID_DceLimitCaptainData, "DceLimitCaptainData"),
                this._pkgMap.AddPkg(t.ID_DcePromoteCaptain, "DcePromoteCaptain"),
                this._pkgMap.AddPkg(t.ID_DceRecruitCaptain, "DceRecruitCaptain"),
                this._pkgMap.AddPkg(t.ID_DceUpgradeCaptain, "DceUpgradeCaptain"),
                this._pkgMap.AddPkg(t.ID_DceUseSuperCaptainGift, "DceUseSuperCaptainGift"),
                this._pkgMap.AddPkg(t.ID_DceLimitShipBuyItem, "DceLimitShipBuyItem"),
                this._pkgMap.AddPkg(t.ID_DceBuyLimitCaptain, "DceBuyLimitCaptain"),
                this._pkgMap.AddPkg(t.ID_DceBuyGhostShip, "DceBuyGhostShip"),
                this._pkgMap.AddPkg(t.ID_DceCampBattleSetTrustee, "DceCampBattleSetTrustee"),
                this._pkgMap.AddPkg(t.ID_DceMedalPromote, "DceMedalPromote"),
                this._pkgMap.AddPkg(t.ID_DceSoulDecompose, "DceSoulDecompose"),
                this._pkgMap.AddPkg(t.ID_DceSoulRestore, "DceSoulRestore"),
                this._pkgMap.AddPkg(t.ID_DceSuperExchangeInfo, "DceSuperExchangeInfo"),
                this._pkgMap.AddPkg(t.ID_DceSuperExchangeItem, "DceSuperExchangeItem"),
                this._pkgMap.AddPkg(t.ID_DceGuildScienceList, "DceGuildScienceList"),
                this._pkgMap.AddPkg(t.ID_DceUpgradeGuildScience, "DceUpgradeGuildScience"),
                this._pkgMap.AddPkg(t.ID_DceClearGuildBattleCD, "DceClearGuildBattleCD"),
                this._pkgMap.AddPkg(t.ID_DceGuildBattleBuy, "DceGuildBattleBuy"),
                this._pkgMap.AddPkg(t.ID_DceGuildBattleData, "DceGuildBattleData"),
                this._pkgMap.AddPkg(t.ID_DceGuildBattleEnter, "DceGuildBattleEnter"),
                this._pkgMap.AddPkg(t.ID_DceGuildBattleMove, "DceGuildBattleMove"),
                this._pkgMap.AddPkg(t.ID_DceGuildBattlePrepare, "DceGuildBattlePrepare"),
                this._pkgMap.AddPkg(t.ID_DceGuildBattleRankList, "DceGuildBattleRankList"),
                this._pkgMap.AddPkg(t.ID_DceGuildBattleResult, "DceGuildBattleResult"),
                this._pkgMap.AddPkg(t.ID_DceGuildBattleSignUp, "DceGuildBattleSignUp"),
                this._pkgMap.AddPkg(t.ID_DceGuildBattleSignUpList, "DceGuildBattleSignUpList"),
                this._pkgMap.AddPkg(t.ID_DceGoldIslandOpen, "DceGoldIslandOpen"),
                this._pkgMap.AddPkg(t.ID_DceGoldIslandSearch, "DceGoldIslandSearch"),
                this._pkgMap.AddPkg(t.ID_DceGoldIslandOccupy, "DceGoldIslandOccupy"),
                this._pkgMap.AddPkg(t.ID_DceGoldIslandHelp, "DceGoldIslandHelp"),
                this._pkgMap.AddPkg(t.ID_DceGoldIslandInviteHelp, "DceGoldIslandInviteHelp"),
                this._pkgMap.AddPkg(t.ID_DceGoldIslandDelayTime, "DceGoldIslandDelayTime"),
                this._pkgMap.AddPkg(t.ID_DceGoldIslandInviteMemberlist, "DceGoldIslandInviteMemberlist"),
                this._pkgMap.AddPkg(t.ID_DceGoldIslandAgreeApply, "DceGoldIslandAgreeApply"),
                this._pkgMap.AddPkg(t.ID_DceGoldIslandApplyHelp, "DceGoldIslandApplyHelp"),
                this._pkgMap.AddPkg(t.ID_DceGoldIslandCancel, "DceGoldIslandCancel"),
                this._pkgMap.AddPkg(t.ID_DceChangeRole, "DceChangeRole"),
                this._pkgMap.AddPkg(t.ID_DceArmadaData, "DceArmadaData"),
                this._pkgMap.AddPkg(t.ID_DceLimitTimeShopBuy, "DceLimitTimeShopBuy"),
                this._pkgMap.AddPkg(t.ID_DceLimitTimeShopInfo, "DceLimitTimeShopInfo"),
                this._pkgMap.AddPkg(t.ID_DceComposeSouls, "DceComposeSouls"),
                this._pkgMap.AddPkg(t.ID_DceSoulPieceList, "DceSoulPieceList"),
                this._pkgMap.AddPkg(t.ID_DceGetTaskReward, "DceGetTaskReward"),
                this._pkgMap.AddPkg(t.ID_DceTaskRewardData, "DceTaskRewardData"),
                this._pkgMap.AddPkg(t.ID_DceExchangeCaptainCount, "DceExchangeCaptainCount"),
                this._pkgMap.AddPkg(t.ID_DcePlotCopyWarBattleInfo, "DcePlotCopyWarBattleInfo"),
                this._pkgMap.AddPkg(t.ID_DcePlotCopyWarEnter, "DcePlotCopyWarEnter"),
                this._pkgMap.AddPkg(t.ID_DcePlotCopyWarMove, "DcePlotCopyWarMove"),
                this._pkgMap.AddPkg(t.ID_DcePlotCopyWarRollStep, "DcePlotCopyWarRollStep"),
                this._pkgMap.AddPkg(t.ID_DceActivateTalent, "DceActivateTalent"),
                this._pkgMap.AddPkg(t.ID_DceTalentList, "DceTalentList"),
                this._pkgMap.AddPkg(t.ID_DceUpgradeTalent, "DceUpgradeTalent"),
                this._pkgMap.AddPkg(t.ID_DcePlotCopyWarOpen, "DcePlotCopyWarOpen"),
                this._pkgMap.AddPkg(t.ID_DceAutoUpgradeScience, "DceAutoUpgradeScience"),
                this._pkgMap.AddPkg(t.ID_DceGlobalArenaBack, "DceGlobalArenaBack"),
                this._pkgMap.AddPkg(t.ID_DceGlobalArenaBattle, "DceGlobalArenaBattle"),
                this._pkgMap.AddPkg(t.ID_DceGlobalArenaBattleProgress, "DceGlobalArenaBattleProgress"),
                this._pkgMap.AddPkg(t.ID_DceGlobalArenaData, "DceGlobalArenaData"),
                this._pkgMap.AddPkg(t.ID_DceGlobalArenaEncourage, "DceGlobalArenaEncourage"),
                this._pkgMap.AddPkg(t.ID_DceGlobalArenaPlayOffList, "DceGlobalArenaPlayOffList"),
                this._pkgMap.AddPkg(t.ID_DceGlobalArenaProstrate, "DceGlobalArenaProstrate"),
                this._pkgMap.AddPkg(t.ID_DceGlobalArenaSelfInfo, "DceGlobalArenaSelfInfo"),
                this._pkgMap.AddPkg(t.ID_DceGlobalArenaUpdateTactic, "DceGlobalArenaUpdateTactic"),
                this._pkgMap.AddPkg(t.ID_DceSignUpAudition, "DceSignUpAudition"),
                this._pkgMap.AddPkg(t.ID_DceSalute, "DceSalute"),
                this._pkgMap.AddPkg(t.ID_DceSaluteData, "DceSaluteData"),
                this._pkgMap.AddPkg(t.ID_DceGoldLeaderExplore, "DceGoldLeaderExplore"),
                this._pkgMap.AddPkg(t.ID_DceGoldLeaderGetOrder, "DceGoldLeaderGetOrder"),
                this._pkgMap.AddPkg(t.ID_DceGoldLeaderInfo, "DceGoldLeaderInfo"),
                this._pkgMap.AddPkg(t.ID_DceGoldLeaderBuyOrder, "DceGoldLeaderBuyOrder"),
                this._pkgMap.AddPkg(t.ID_DceLuckyGodBuyItem, "DceLuckyGodBuyItem"),
                this._pkgMap.AddPkg(t.ID_DceMonthCardData, "DceMonthCardData"),
                this._pkgMap.AddPkg(t.ID_DceGlobalArenaChamption, "DceGlobalArenaChamption"),
                this._pkgMap.AddPkg(t.ID_DceAutoEquipSeikoSoldier, "DceAutoEquipSeikoSoldier"),
                this._pkgMap.AddPkg(t.ID_DceComposeSeiko, "DceComposeSeiko"),
                this._pkgMap.AddPkg(t.ID_DceDecomposeSeiko, "DceDecomposeSeiko"),
                this._pkgMap.AddPkg(t.ID_DceEquipSeiko, "DceEquipSeiko"),
                this._pkgMap.AddPkg(t.ID_DceForgeSeiko, "DceForgeSeiko"),
                this._pkgMap.AddPkg(t.ID_DceReductionSeiko, "DceReductionSeiko"),
                this._pkgMap.AddPkg(t.ID_DceReductionSeikoInfo, "DceReductionSeikoInfo"),
                this._pkgMap.AddPkg(t.ID_DceRemouldSeiko, "DceRemouldSeiko"),
                this._pkgMap.AddPkg(t.ID_DceSeikoList, "DceSeikoList"),
                this._pkgMap.AddPkg(t.ID_DceSeikoPieceList, "DceSeikoPieceList"),
                this._pkgMap.AddPkg(t.ID_DceUnEquipSeiko, "DceUnEquipSeiko"),
                this._pkgMap.AddPkg(t.ID_DceUpgradeSeiko, "DceUpgradeSeiko"),
                this._pkgMap.AddPkg(t.ID_DceSaveForge, "DceSaveForge"),
                this._pkgMap.AddPkg(t.ID_DceEnterStageTower, "DceEnterStageTower"),
                this._pkgMap.AddPkg(t.ID_DceSetTacticForStageTower, "DceSetTacticForStageTower"),
                this._pkgMap.AddPkg(t.ID_DceGetTacticForStageTower, "DceGetTacticForStageTower"),
                this._pkgMap.AddPkg(t.ID_DceUpdateEnemyForStageTower, "DceUpdateEnemyForStageTower"),
                this._pkgMap.AddPkg(t.ID_DceStageTowerPurchaseAndResurr, "DceStageTowerPurchaseAndResurr"),
                this._pkgMap.AddPkg(t.ID_DceFindEnemyForStageTower, "DceFindEnemyForStageTower"),
                this._pkgMap.AddPkg(t.ID_DceSeikoShopData, "DceSeikoShopData"),
                this._pkgMap.AddPkg(t.ID_DceSeikoShopHandle, "DceSeikoShopHandle"),
                this._pkgMap.AddPkg(t.ID_DceOnearmedBanditTen, "DceOnearmedBanditTen"),
                this._pkgMap.AddPkg(t.ID_DcePaperLockOperation, "DcePaperLockOperation"),
                this._pkgMap.AddPkg(t.ID_DceShipLockOperation, "DceShipLockOperation"),
                this._pkgMap.AddPkg(t.ID_DceCaptainLockOpt, "DceCaptainLockOpt"),
                this._pkgMap.AddPkg(t.ID_DceRenameGuild, "DceRenameGuild"),
                this._pkgMap.AddPkg(t.ID_DceSeikoLockOpt, "DceSeikoLockOpt"),
                this._pkgMap.AddPkg(t.ID_DceSoulLockOpt, "DceSoulLockOpt"),
                this._pkgMap.AddPkg(t.ID_DcePartsLockOpt, "DcePartsLockOpt"),
                this._pkgMap.AddPkg(t.ID_DceGoldIslandCancelHelped, "DceGoldIslandCancelHelped"),
                this._pkgMap.AddPkg(t.ID_DceGlobalArenaCheckEncourage, "DceGlobalArenaCheckEncourage"),
                this._pkgMap.AddPkg(t.ID_DceGuildBattleAuto, "DceGuildBattleAuto"),
                this._pkgMap.AddPkg(t.ID_DceTuanGouOpt, "DceTuanGouOpt"),
                this._pkgMap.AddPkg(t.ID_DceStageTowerAcityData, "DceStageTowerAcityData"),
                this._pkgMap.AddPkg(t.ID_DceStageTowerAcityHandle, "DceStageTowerAcityHandle"),
                this._pkgMap.AddPkg(t.ID_DceSeiKoExchange, "DceSeiKoExchange"),
                this._pkgMap.AddPkg(t.ID_DceSeiKoScore, "DceSeiKoScore"),
                this._pkgMap.AddPkg(t.ID_DceWeal, "DceWeal"),
                this._pkgMap.AddPkg(t.ID_DceRechargeBackGift, "DceRechargeBackGift"),
                this._pkgMap.AddPkg(t.ID_DceRechargeBackGiftEnter, "DceRechargeBackGiftEnter"),
                this._pkgMap.AddPkg(t.ID_DceCenterCampBattleCampRank, "DceCenterCampBattleCampRank"),
                this._pkgMap.AddPkg(t.ID_DceUseSoulGift, "DceUseSoulGift"),
                this._pkgMap.AddPkg(t.ID_DceAutoEquipSoul, "DceAutoEquipSoul"),
                this._pkgMap.AddPkg(t.ID_DceUnAutoEquipSoul, "DceUnAutoEquipSoul"),
                this._pkgMap.AddPkg(t.ID_DceGlobalGuildBattleSign, "DceGlobalGuildBattleSign"),
                this._pkgMap.AddPkg(t.ID_DceGlobalGuildBattleAdjust, "DceGlobalGuildBattleAdjust"),
                this._pkgMap.AddPkg(t.ID_DceGlobalGuildBattleEncourage, "DceGlobalGuildBattleEncourage"),
                this._pkgMap.AddPkg(t.ID_DceGlobalGuildBattleUpdate, "DceGlobalGuildBattleUpdate"),
                this._pkgMap.AddPkg(t.ID_DceGlobalGuildBattleData, "DceGlobalGuildBattleData"),
                this._pkgMap.AddPkg(t.ID_DceGlobalGuildBattleSeeMember, "DceGlobalGuildBattleSeeMember"),
                this._pkgMap.AddPkg(t.ID_DceGlobalGuildBattleProstrate, "DceGlobalGuildBattleProstrate"),
                this._pkgMap.AddPkg(t.ID_DceGlobalGuildBattleGuildGroupVs, "DceGlobalGuildBattleGuildGroupVs"),
                this._pkgMap.AddPkg(t.ID_DceGlobalGuildBattleGuildVs, "DceGlobalGuildBattleGuildVs"),
                this._pkgMap.AddPkg(t.ID_DceGlobalGuildBattleVsBattle, "DceGlobalGuildBattleVsBattle"),
                this._pkgMap.AddPkg(t.ID_DceScoutGuild, "DceScoutGuild"),
                this._pkgMap.AddPkg(t.ID_DceGlobalGuildBattleChamptionMember, "DceGlobalGuildBattleChamptionMember"),
                this._pkgMap.AddPkg(t.ID_DceGlobalGuildBattleChamptionList, "DceGlobalGuildBattleChamptionList"),
                this._pkgMap.AddPkg(t.ID_DceActivityWebData, "DceActivityWebData"),
                this._pkgMap.AddPkg(t.ID_DceFocusAward, "DceFocusAward"),
                this._pkgMap.AddPkg(t.ID_DceExchangeCode, "DceExchangeCode"),
                this._pkgMap.AddPkg(t.ID_DseAccBind, "DseAccBind"),
                this._pkgMap.AddPkg(t.ID_DseActiveTips, "DseActiveTips"),
                this._pkgMap.AddPkg(t.ID_DseActivity, "DseActivity"),
                this._pkgMap.AddPkg(t.ID_DseActivityData, "DseActivityData"),
                this._pkgMap.AddPkg(t.ID_DseAddFriend, "DseAddFriend"),
                this._pkgMap.AddPkg(t.ID_DseAddMail, "DseAddMail"),
                this._pkgMap.AddPkg(t.ID_DseAddOwnedPaper, "DseAddOwnedPaper"),
                this._pkgMap.AddPkg(t.ID_DseAddParts, "DseAddParts"),
                this._pkgMap.AddPkg(t.ID_DseAddShip, "DseAddShip"),
                this._pkgMap.AddPkg(t.ID_DseAllLastID, "DseAllLastID"),
                this._pkgMap.AddPkg(t.ID_DseApplyList, "DseApplyList"),
                this._pkgMap.AddPkg(t.ID_DseArenaData, "DseArenaData"),
                this._pkgMap.AddPkg(t.ID_DseArenaExchange, "DseArenaExchange"),
                this._pkgMap.AddPkg(t.ID_DseArenaList, "DseArenaList"),
                this._pkgMap.AddPkg(t.ID_DseAuthState, "DseAuthState"),
                this._pkgMap.AddPkg(t.ID_DseAutoEquipSoldier, "DseAutoEquipSoldier"),
                this._pkgMap.AddPkg(t.ID_DseAwardCenter, "DseAwardCenter"),
                this._pkgMap.AddPkg(t.ID_DseBattleInfo, "DseBattleInfo"),
                this._pkgMap.AddPkg(t.ID_DseBattleReview, "DseBattleReview"),
                this._pkgMap.AddPkg(t.ID_DseBattleStart, "DseBattleStart"),
                this._pkgMap.AddPkg(t.ID_DseBattleStartBySweep, "DseBattleStartBySweep"),
                this._pkgMap.AddPkg(t.ID_DseBlackList, "DseBlackList"),
                this._pkgMap.AddPkg(t.ID_DseBlackListOpt, "DseBlackListOpt"),
                this._pkgMap.AddPkg(t.ID_DseBroadcast, "DseBroadcast"),
                this._pkgMap.AddPkg(t.ID_DseBuy, "DseBuy"),
                this._pkgMap.AddPkg(t.ID_DseBuyGuard, "DseBuyGuard"),
                this._pkgMap.AddPkg(t.ID_DseBuyOil, "DseBuyOil"),
                this._pkgMap.AddPkg(t.ID_DseCampBattleData, "DseCampBattleData"),
                this._pkgMap.AddPkg(t.ID_DseCampBattleMove, "DseCampBattleMove"),
                this._pkgMap.AddPkg(t.ID_DseCampBattleMsg, "DseCampBattleMsg"),
                this._pkgMap.AddPkg(t.ID_DseCampBattleResult, "DseCampBattleResult"),
                this._pkgMap.AddPkg(t.ID_DseChargePaper, "DseChargePaper"),
                this._pkgMap.AddPkg(t.ID_DseChat, "DseChat"),
                this._pkgMap.AddPkg(t.ID_DseChatData, "DseChatData"),
                this._pkgMap.AddPkg(t.ID_DseChatMsg, "DseChatMsg"),
                this._pkgMap.AddPkg(t.ID_DseChatMsgLog, "DseChatMsgLog"),
                this._pkgMap.AddPkg(t.ID_DseCheckPlayerName, "DseCheckPlayerName"),
                this._pkgMap.AddPkg(t.ID_DseChristmasMineral, "DseChristmasMineral"),
                this._pkgMap.AddPkg(t.ID_DseChristmasMineralStart, "DseChristmasMineralStart"),
                this._pkgMap.AddPkg(t.ID_DseChristmasScroeExchange, "DseChristmasScroeExchange"),
                this._pkgMap.AddPkg(t.ID_DseChritmasLogin, "DseChritmasLogin"),
                this._pkgMap.AddPkg(t.ID_DseChritmasLottery, "DseChritmasLottery"),
                this._pkgMap.AddPkg(t.ID_DseChritmasLotteryDropList, "DseChritmasLotteryDropList"),
                this._pkgMap.AddPkg(t.ID_DseChritmasLotteryStart, "DseChritmasLotteryStart"),
                this._pkgMap.AddPkg(t.ID_DseClearCampBattleCD, "DseClearCampBattleCD"),
                this._pkgMap.AddPkg(t.ID_DseComposeParts, "DseComposeParts"),
                this._pkgMap.AddPkg(t.ID_DseConsumeExchange, "DseConsumeExchange"),
                this._pkgMap.AddPkg(t.ID_DseConsumeExchangeData, "DseConsumeExchangeData"),
                this._pkgMap.AddPkg(t.ID_DseCreateGuild, "DseCreateGuild"),
                this._pkgMap.AddPkg(t.ID_DseCreateShip, "DseCreateShip"),
                this._pkgMap.AddPkg(t.ID_DseDayLimitFightData, "DseDayLimitFightData"),
                this._pkgMap.AddPkg(t.ID_DseDecomposeParts, "DseDecomposeParts"),
                this._pkgMap.AddPkg(t.ID_DseDeleteFriend, "DseDeleteFriend"),
                this._pkgMap.AddPkg(t.ID_DseDelParts, "DseDelParts"),
                this._pkgMap.AddPkg(t.ID_DseDelShip, "DseDelShip"),
                this._pkgMap.AddPkg(t.ID_DseDrawAllElectric, "DseDrawAllElectric"),
                this._pkgMap.AddPkg(t.ID_DseDrawElectric, "DseDrawElectric"),
                this._pkgMap.AddPkg(t.ID_DseEnterArena, "DseEnterArena"),
                this._pkgMap.AddPkg(t.ID_DseEnterCampBattle, "DseEnterCampBattle"),
                this._pkgMap.AddPkg(t.ID_DseEnterGuard, "DseEnterGuard"),
                this._pkgMap.AddPkg(t.ID_DseEquipParts, "DseEquipParts"),
                this._pkgMap.AddPkg(t.ID_DseEquipSoul, "DseEquipSoul"),
                this._pkgMap.AddPkg(t.ID_DseFriendList, "DseFriendList"),
                this._pkgMap.AddPkg(t.ID_DseFuncSwich, "DseFuncSwich"),
                this._pkgMap.AddPkg(t.ID_DseGetAward, "DseGetAward"),
                this._pkgMap.AddPkg(t.ID_DseGetCenterGold, "DseGetCenterGold"),
                this._pkgMap.AddPkg(t.ID_DseGetDayLimitFight, "DseGetDayLimitFight"),
                this._pkgMap.AddPkg(t.ID_DseGetGuardRank, "DseGetGuardRank"),
                this._pkgMap.AddPkg(t.ID_DseGetMailProp, "DseGetMailProp"),
                this._pkgMap.AddPkg(t.ID_DseGetMedal, "DseGetMedal"),
                this._pkgMap.AddPkg(t.ID_DseGetTactic, "DseGetTactic"),
                this._pkgMap.AddPkg(t.ID_DseGetWeakCamp, "DseGetWeakCamp"),
                this._pkgMap.AddPkg(t.ID_DseGhostShip, "DseGhostShip"),
                this._pkgMap.AddPkg(t.ID_DseGhostShipData, "DseGhostShipData"),
                this._pkgMap.AddPkg(t.ID_DseGuardStage, "DseGuardStage"),
                this._pkgMap.AddPkg(t.ID_DseGuildApply, "DseGuildApply"),
                this._pkgMap.AddPkg(t.ID_DseGuildApplyList, "DseGuildApplyList"),
                this._pkgMap.AddPkg(t.ID_DseGuildApproval, "DseGuildApproval"),
                this._pkgMap.AddPkg(t.ID_DseGuildBuyGift, "DseGuildBuyGift"),
                this._pkgMap.AddPkg(t.ID_DseGuildCancelApply, "DseGuildCancelApply"),
                this._pkgMap.AddPkg(t.ID_DseGuildData, "DseGuildData"),
                this._pkgMap.AddPkg(t.ID_DseGuildDemise, "DseGuildDemise"),
                this._pkgMap.AddPkg(t.ID_DseGuildDismiss, "DseGuildDismiss"),
                this._pkgMap.AddPkg(t.ID_DseGuildDismissCancel, "DseGuildDismissCancel"),
                this._pkgMap.AddPkg(t.ID_DseGuildDonate, "DseGuildDonate"),
                this._pkgMap.AddPkg(t.ID_DseGuildExpel, "DseGuildExpel"),
                this._pkgMap.AddPkg(t.ID_DseGuildFireDeputy, "DseGuildFireDeputy"),
                this._pkgMap.AddPkg(t.ID_DseGuildInvite, "DseGuildInvite"),
                this._pkgMap.AddPkg(t.ID_DseGuildList, "DseGuildList"),
                this._pkgMap.AddPkg(t.ID_DseGuildMemberList, "DseGuildMemberList"),
                this._pkgMap.AddPkg(t.ID_DseGuildQuit, "DseGuildQuit"),
                this._pkgMap.AddPkg(t.ID_DseGuildSetDeputy, "DseGuildSetDeputy"),
                this._pkgMap.AddPkg(t.ID_DseGuildSetMedal, "DseGuildSetMedal"),
                this._pkgMap.AddPkg(t.ID_DseGuildUpgrade, "DseGuildUpgrade"),
                this._pkgMap.AddPkg(t.ID_DseHeartbeat, "DseHeartbeat"),
                this._pkgMap.AddPkg(t.ID_DseInvitedList, "DseInvitedList"),
                this._pkgMap.AddPkg(t.ID_DseInviteFriend, "DseInviteFriend"),
                this._pkgMap.AddPkg(t.ID_DseLimitShip, "DseLimitShip"),
                this._pkgMap.AddPkg(t.ID_DseLimitShipData, "DseLimitShipData"),
                this._pkgMap.AddPkg(t.ID_DseLuckyGoddessData, "DseLuckyGoddessData"),
                this._pkgMap.AddPkg(t.ID_DseLuckyGoddessForCharge, "DseLuckyGoddessForCharge"),
                this._pkgMap.AddPkg(t.ID_DseLuckyGoddessForFree, "DseLuckyGoddessForFree"),
                this._pkgMap.AddPkg(t.ID_DseLuckyWheelActivity, "DseLuckyWheelActivity"),
                this._pkgMap.AddPkg(t.ID_DseLuckyWheelActivityData, "DseLuckyWheelActivityData"),
                this._pkgMap.AddPkg(t.ID_DseMailList, "DseMailList"),
                this._pkgMap.AddPkg(t.ID_DseMedalData, "DseMedalData"),
                this._pkgMap.AddPkg(t.ID_DseMilitaryRankGetDailyReward, "DseMilitaryRankGetDailyReward"),
                this._pkgMap.AddPkg(t.ID_DseMilitaryRankInfo, "DseMilitaryRankInfo"),
                this._pkgMap.AddPkg(t.ID_DseMilitaryRankUpgrad, "DseMilitaryRankUpgrad"),
                this._pkgMap.AddPkg(t.ID_DseMisteryShopRefresh, "DseMisteryShopRefresh"),
                this._pkgMap.AddPkg(t.ID_DseModifyDeclaration, "DseModifyDeclaration"),
                this._pkgMap.AddPkg(t.ID_DseModifyNotify, "DseModifyNotify"),
                this._pkgMap.AddPkg(t.ID_DseMonthCard, "DseMonthCard"),
                this._pkgMap.AddPkg(t.ID_DseMonthSignTake, "DseMonthSignTake"),
                this._pkgMap.AddPkg(t.ID_DseNewDay, "DseNewDay"),
                this._pkgMap.AddPkg(t.ID_DseOwnedPaper, "DseOwnedPaper"),
                this._pkgMap.AddPkg(t.ID_DseOwnedPaperFirstFlag, "DseOwnedPaperFirstFlag"),
                this._pkgMap.AddPkg(t.ID_DsePaperChargeCount, "DsePaperChargeCount"),
                this._pkgMap.AddPkg(t.ID_DsePaperList, "DsePaperList"),
                this._pkgMap.AddPkg(t.ID_DsePaperPieceList, "DsePaperPieceList"),
                this._pkgMap.AddPkg(t.ID_DsePartPieceList, "DsePartPieceList"),
                this._pkgMap.AddPkg(t.ID_DsePartsList, "DsePartsList"),
                this._pkgMap.AddPkg(t.ID_DsePropList, "DsePropList"),
                this._pkgMap.AddPkg(t.ID_DseQuestionAnswer, "DseQuestionAnswer"),
                this._pkgMap.AddPkg(t.ID_DseQuestionList, "DseQuestionList"),
                this._pkgMap.AddPkg(t.ID_DseQuestionRank, "DseQuestionRank"),
                this._pkgMap.AddPkg(t.ID_DseRankList, "DseRankList"),
                this._pkgMap.AddPkg(t.ID_DseRecElectricList, "DseRecElectricList"),
                this._pkgMap.AddPkg(t.ID_DseRecommandInviteList, "DseRecommandInviteList"),
                this._pkgMap.AddPkg(t.ID_DseRefuseAddFriend, "DseRefuseAddFriend"),
                this._pkgMap.AddPkg(t.ID_DseRemouldParts, "DseRemouldParts"),
                this._pkgMap.AddPkg(t.ID_DseRemouldShip, "DseRemouldShip"),
                this._pkgMap.AddPkg(t.ID_DseRenameRole, "DseRenameRole"),
                this._pkgMap.AddPkg(t.ID_DseRenameShip, "DseRenameShip"),
                this._pkgMap.AddPkg(t.ID_DseResetGuard, "DseResetGuard"),
                this._pkgMap.AddPkg(t.ID_DseResetStageCount, "DseResetStageCount"),
                this._pkgMap.AddPkg(t.ID_DseRetireShip, "DseRetireShip"),
                this._pkgMap.AddPkg(t.ID_DseRobberyList, "DseRobberyList"),
                this._pkgMap.AddPkg(t.ID_DseSalePaper, "DseSalePaper"),
                this._pkgMap.AddPkg(t.ID_DseScienceList, "DseScienceList"),
                this._pkgMap.AddPkg(t.ID_DseScoutSoldier, "DseScoutSoldier"),
                this._pkgMap.AddPkg(t.ID_DseSearchGuild, "DseSearchGuild"),
                this._pkgMap.AddPkg(t.ID_DseSearchPlayer, "DseSearchPlayer"),
                this._pkgMap.AddPkg(t.ID_DseSellProp, "DseSellProp"),
                this._pkgMap.AddPkg(t.ID_DseSendElectric, "DseSendElectric"),
                this._pkgMap.AddPkg(t.ID_DseSendMail, "DseSendMail"),
                this._pkgMap.AddPkg(t.ID_DseSetCaption, "DseSetCaption"),
                this._pkgMap.AddPkg(t.ID_DseSetRole, "DseSetRole"),
                this._pkgMap.AddPkg(t.ID_DseSetSoldier, "DseSetSoldier"),
                this._pkgMap.AddPkg(t.ID_DseSetTactic, "DseSetTactic"),
                this._pkgMap.AddPkg(t.ID_DseSetVerifyOptions, "DseSetVerifyOptions"),
                this._pkgMap.AddPkg(t.ID_DseSevenDaysExchange, "DseSevenDaysExchange"),
                this._pkgMap.AddPkg(t.ID_DseSevenDaysExchangeData, "DseSevenDaysExchangeData"),
                this._pkgMap.AddPkg(t.ID_DseShipList, "DseShipList"),
                this._pkgMap.AddPkg(t.ID_DseShopData, "DseShopData"),
                this._pkgMap.AddPkg(t.ID_DseSoldierList, "DseSoldierList"),
                this._pkgMap.AddPkg(t.ID_DseSoul, "DseSoul"),
                this._pkgMap.AddPkg(t.ID_DseSoulEat, "DseSoulEat"),
                this._pkgMap.AddPkg(t.ID_DseSoulList, "DseSoulList"),
                this._pkgMap.AddPkg(t.ID_DseSpy, "DseSpy"),
                this._pkgMap.AddPkg(t.ID_DseSpyData, "DseSpyData"),
                this._pkgMap.AddPkg(t.ID_DseStageData, "DseStageData"),
                this._pkgMap.AddPkg(t.ID_DseStageList, "DseStageList"),
                this._pkgMap.AddPkg(t.ID_DseStartServerActivity, "DseStartServerActivity"),
                this._pkgMap.AddPkg(t.ID_DseTrain, "DseTrain"),
                this._pkgMap.AddPkg(t.ID_DseUnEquipParts, "DseUnEquipParts"),
                this._pkgMap.AddPkg(t.ID_DseUnEquipSoul, "DseUnEquipSoul"),
                this._pkgMap.AddPkg(t.ID_DseUpdateMail, "DseUpdateMail"),
                this._pkgMap.AddPkg(t.ID_DseUpdateParts, "DseUpdateParts"),
                this._pkgMap.AddPkg(t.ID_DseUpdateShip, "DseUpdateShip"),
                this._pkgMap.AddPkg(t.ID_DseUpgradeBuild, "DseUpgradeBuild"),
                this._pkgMap.AddPkg(t.ID_DseUpgradeParts, "DseUpgradeParts"),
                this._pkgMap.AddPkg(t.ID_DseUpgradeScience, "DseUpgradeScience"),
                this._pkgMap.AddPkg(t.ID_DseUpgradeShip, "DseUpgradeShip"),
                this._pkgMap.AddPkg(t.ID_DseUpgradeSkill, "DseUpgradeSkill"),
                this._pkgMap.AddPkg(t.ID_DseUseProp, "DseUseProp"),
                this._pkgMap.AddPkg(t.ID_DseUserComeBack, "DseUserComeBack"),
                this._pkgMap.AddPkg(t.ID_DseUserComeBackReward, "DseUserComeBackReward"),
                this._pkgMap.AddPkg(t.ID_DseUserData, "DseUserData"),
                this._pkgMap.AddPkg(t.ID_DseGoddessReward, "DseGoddessReward"),
                this._pkgMap.AddPkg(t.ID_DseGoddessRewardData, "DseGoddessRewardData"),
                this._pkgMap.AddPkg(t.ID_DseLuckyCatDataRequest, "DseLuckyCatDataRequest"),
                this._pkgMap.AddPkg(t.ID_DseLuckyCatRequest, "DseLuckyCatRequest"),
                this._pkgMap.AddPkg(t.ID_DseLuckBoxPointExchange, "DseLuckBoxPointExchange"),
                this._pkgMap.AddPkg(t.ID_DseLuckBoxPointExchangeOpen, "DseLuckBoxPointExchangeOpen"),
                this._pkgMap.AddPkg(t.ID_DseLoginPokerOpen, "DseLoginPokerOpen"),
                this._pkgMap.AddPkg(t.ID_DseLoginPokerAction, "DseLoginPokerAction"),
                this._pkgMap.AddPkg(t.ID_DseLoginPokerFinal, "DseLoginPokerFinal"),
                this._pkgMap.AddPkg(t.ID_DseReductionParts, "DseReductionParts"),
                this._pkgMap.AddPkg(t.ID_DseBonusFlyDataRequest, "DseBonusFlyDataRequest"),
                this._pkgMap.AddPkg(t.ID_DseBonusFlyRequest, "DseBonusFlyRequest"),
                this._pkgMap.AddPkg(t.ID_DseRechargeSevenDayRequest, "DseRechargeSevenDayRequest"),
                this._pkgMap.AddPkg(t.ID_DseRechargeSevenDayRequestData, "DseRechargeSevenDayRequestData"),
                this._pkgMap.AddPkg(t.ID_DseCenterCampBattleData, "DseCenterCampBattleData"),
                this._pkgMap.AddPkg(t.ID_DseCenterCampBattleMove, "DseCenterCampBattleMove"),
                this._pkgMap.AddPkg(t.ID_DseCenterCampBattleMsg, "DseCenterCampBattleMsg"),
                this._pkgMap.AddPkg(t.ID_DseCenterCampBattleResult, "DseCenterCampBattleResult"),
                this._pkgMap.AddPkg(t.ID_DseClearCenterCampBattleCD, "DseClearCenterCampBattleCD"),
                this._pkgMap.AddPkg(t.ID_DseEnterCenterCampBattle, "DseEnterCenterCampBattle"),
                this._pkgMap.AddPkg(t.ID_DseReductionPartsInfo, "DseReductionPartsInfo"),
                this._pkgMap.AddPkg(t.ID_DseUsePaperPieceGift, "DseUsePaperPieceGift"),
                this._pkgMap.AddPkg(t.ID_DseOnearmedBanditDataRequest, "DseOnearmedBanditDataRequest"),
                this._pkgMap.AddPkg(t.ID_DseOnearmedBanditRequest, "DseOnearmedBanditRequest"),
                this._pkgMap.AddPkg(t.ID_DseValentineDataRequest, "DseValentineDataRequest"),
                this._pkgMap.AddPkg(t.ID_DseValentineGiveGift, "DseValentineGiveGift"),
                this._pkgMap.AddPkg(t.ID_DseCampBattleBuy, "DseCampBattleBuy"),
                this._pkgMap.AddPkg(t.ID_DseCenterCampBattleBuy, "DseCenterCampBattleBuy"),
                this._pkgMap.AddPkg(t.ID_DseAddSoulOwnedPaper, "DseAddSoulOwnedPaper"),
                this._pkgMap.AddPkg(t.ID_DseOwnedSoulPaperFirstFlag, "DseOwnedSoulPaperFirstFlag"),
                this._pkgMap.AddPkg(t.ID_DseLuckyGoddnessForCharge, "DseLuckyGoddnessForCharge"),
                this._pkgMap.AddPkg(t.ID_DseShipFormationInfo, "DseShipFormationInfo"),
                this._pkgMap.AddPkg(t.ID_DseShipFormationLevelUp, "DseShipFormationLevelUp"),
                this._pkgMap.AddPkg(t.ID_DseShipFormationStarUp, "DseShipFormationStarUp"),
                this._pkgMap.AddPkg(t.ID_DseShipFormationAddNotice, "DseShipFormationAddNotice"),
                this._pkgMap.AddPkg(t.ID_DseShipFormationChoose, "DseShipFormationChoose"),
                this._pkgMap.AddPkg(t.ID_DseShipFormationFistFlag, "DseShipFormationFistFlag"),
                this._pkgMap.AddPkg(t.ID_DseRegSecondDayGift, "DseRegSecondDayGift"),
                this._pkgMap.AddPkg(t.ID_DseBuySpyItem, "DseBuySpyItem"),
                this._pkgMap.AddPkg(t.ID_DseChallengeDataRequest, "DseChallengeDataRequest"),
                this._pkgMap.AddPkg(t.ID_DseChallengeSignUp, "DseChallengeSignUp"),
                this._pkgMap.AddPkg(t.ID_DseChallengeFight, "DseChallengeFight"),
                this._pkgMap.AddPkg(t.ID_DseChallengeAction, "DseChallengeAction"),
                this._pkgMap.AddPkg(t.ID_DseChallengeEnemyData, "DseChallengeEnemyData"),
                this._pkgMap.AddPkg(t.ID_DseChallengeRevenge, "DseChallengeRevenge"),
                this._pkgMap.AddPkg(t.ID_DseChallengeRefresh, "DseChallengeRefresh"),
                this._pkgMap.AddPkg(t.ID_DseChallengeRank, "DseChallengeRank"),
                this._pkgMap.AddPkg(t.ID_DseChallengeChampion, "DseChallengeChampion"),
                this._pkgMap.AddPkg(t.ID_DseChallengeWorship, "DseChallengeWorship"),
                this._pkgMap.AddPkg(t.ID_DseChallengeBuy, "DseChallengeBuy"),
                this._pkgMap.AddPkg(t.ID_DseChallengeRefreshCharge, "DseChallengeRefreshCharge"),
                this._pkgMap.AddPkg(t.ID_DseBuyRecruitItem, "DseBuyRecruitItem"),
                this._pkgMap.AddPkg(t.ID_DseCaptainData, "DseCaptainData"),
                this._pkgMap.AddPkg(t.ID_DseCaptainList, "DseCaptainList"),
                this._pkgMap.AddPkg(t.ID_DseCaptainPieceList, "DseCaptainPieceList"),
                this._pkgMap.AddPkg(t.ID_DseComposeCaptain, "DseComposeCaptain"),
                this._pkgMap.AddPkg(t.ID_DseEquipCaptain, "DseEquipCaptain"),
                this._pkgMap.AddPkg(t.ID_DseExchangeCaptain, "DseExchangeCaptain"),
                this._pkgMap.AddPkg(t.ID_DseFireCaptain, "DseFireCaptain"),
                this._pkgMap.AddPkg(t.ID_DseLimitCaptain, "DseLimitCaptain"),
                this._pkgMap.AddPkg(t.ID_DseLimitCaptainData, "DseLimitCaptainData"),
                this._pkgMap.AddPkg(t.ID_DsePromoteCaptain, "DsePromoteCaptain"),
                this._pkgMap.AddPkg(t.ID_DseRecruitCaptain, "DseRecruitCaptain"),
                this._pkgMap.AddPkg(t.ID_DseUpdateCaptain, "DseUpdateCaptain"),
                this._pkgMap.AddPkg(t.ID_DseUpgradeCaptain, "DseUpgradeCaptain"),
                this._pkgMap.AddPkg(t.ID_DseCaptainFirstFlag, "DseCaptainFirstFlag"),
                this._pkgMap.AddPkg(t.ID_DseChallengeLogin, "DseChallengeLogin"),
                this._pkgMap.AddPkg(t.ID_DseUseSuperCaptainGift, "DseUseSuperCaptainGift"),
                this._pkgMap.AddPkg(t.ID_DseLimitShipBuyItem, "DseLimitShipBuyItem"),
                this._pkgMap.AddPkg(t.ID_DseBuyLimitCaptain, "DseBuyLimitCaptain"),
                this._pkgMap.AddPkg(t.ID_DseBuyGhostShip, "DseBuyGhostShip"),
                this._pkgMap.AddPkg(t.ID_DseCampBattleSetTrustee, "DseCampBattleSetTrustee"),
                this._pkgMap.AddPkg(t.ID_DseCaptainPaperAdd, "DseCaptainPaperAdd"),
                this._pkgMap.AddPkg(t.ID_DseCaptainPaperFirstFlag, "DseCaptainPaperFirstFlag"),
                this._pkgMap.AddPkg(t.ID_DseMedalPromote, "DseMedalPromote"),
                this._pkgMap.AddPkg(t.ID_DseSoulDecompose, "DseSoulDecompose"),
                this._pkgMap.AddPkg(t.ID_DseSoulRestore, "DseSoulRestore"),
                this._pkgMap.AddPkg(t.ID_DseSuperExchangeInfo, "DseSuperExchangeInfo"),
                this._pkgMap.AddPkg(t.ID_DseSuperExchangeItem, "DseSuperExchangeItem"),
                this._pkgMap.AddPkg(t.ID_DseGuildScienceList, "DseGuildScienceList"),
                this._pkgMap.AddPkg(t.ID_DseUpgradeGuildScience, "DseUpgradeGuildScience"),
                this._pkgMap.AddPkg(t.ID_DseClearGuildBattleCD, "DseClearGuildBattleCD"),
                this._pkgMap.AddPkg(t.ID_DseGuildBattleBuy, "DseGuildBattleBuy"),
                this._pkgMap.AddPkg(t.ID_DseGuildBattleData, "DseGuildBattleData"),
                this._pkgMap.AddPkg(t.ID_DseGuildBattleEnter, "DseGuildBattleEnter"),
                this._pkgMap.AddPkg(t.ID_DseGuildBattleMove, "DseGuildBattleMove"),
                this._pkgMap.AddPkg(t.ID_DseGuildBattleMsg, "DseGuildBattleMsg"),
                this._pkgMap.AddPkg(t.ID_DseGuildBattlePrepare, "DseGuildBattlePrepare"),
                this._pkgMap.AddPkg(t.ID_DseGuildBattleRankList, "DseGuildBattleRankList"),
                this._pkgMap.AddPkg(t.ID_DseGuildBattleResult, "DseGuildBattleResult"),
                this._pkgMap.AddPkg(t.ID_DseGuildBattleSignUp, "DseGuildBattleSignUp"),
                this._pkgMap.AddPkg(t.ID_DseGuildBattleSignUpList, "DseGuildBattleSignUpList"),
                this._pkgMap.AddPkg(t.ID_DseGoldIslandOpen, "DseGoldIslandOpen"),
                this._pkgMap.AddPkg(t.ID_DseGoldIslandSearch, "DseGoldIslandSearch"),
                this._pkgMap.AddPkg(t.ID_DseGoldIslandOccupy, "DseGoldIslandOccupy"),
                this._pkgMap.AddPkg(t.ID_DseGoldIslandHelp, "DseGoldIslandHelp"),
                this._pkgMap.AddPkg(t.ID_DseGoldIslandInviteHelp, "DseGoldIslandInviteHelp"),
                this._pkgMap.AddPkg(t.ID_DseGoldIslandDelayTime, "DseGoldIslandDelayTime"),
                this._pkgMap.AddPkg(t.ID_DseGoldIslandInviteMemberlist, "DseGoldIslandInviteMemberlist"),
                this._pkgMap.AddPkg(t.ID_DseGoldIslandAgreeApply, "DseGoldIslandAgreeApply"),
                this._pkgMap.AddPkg(t.ID_DseGoldIslandApplyHelp, "DseGoldIslandApplyHelp"),
                this._pkgMap.AddPkg(t.ID_DseGoldIslandCancel, "DseGoldIslandCancel"),
                this._pkgMap.AddPkg(t.ID_DseChangeRole, "DseChangeRole"),
                this._pkgMap.AddPkg(t.ID_DseArmadaData, "DseArmadaData"),
                this._pkgMap.AddPkg(t.ID_DseLimitTimeShopBuy, "DseLimitTimeShopBuy"),
                this._pkgMap.AddPkg(t.ID_DseLimitTimeShopInfo, "DseLimitTimeShopInfo"),
                this._pkgMap.AddPkg(t.ID_DseComposeSouls, "DseComposeSouls"),
                this._pkgMap.AddPkg(t.ID_DseSoulPieceList, "DseSoulPieceList"),
                this._pkgMap.AddPkg(t.ID_DseGetTaskReward, "DseGetTaskReward"),
                this._pkgMap.AddPkg(t.ID_DseTaskRewardData, "DseTaskRewardData"),
                this._pkgMap.AddPkg(t.ID_DseExchangeCaptainCount, "DseExchangeCaptainCount"),
                this._pkgMap.AddPkg(t.ID_DsePlotCopyWarBattleInfo, "DsePlotCopyWarBattleInfo"),
                this._pkgMap.AddPkg(t.ID_DsePlotCopyWarData, "DsePlotCopyWarData"),
                this._pkgMap.AddPkg(t.ID_DsePlotCopyWarEnter, "DsePlotCopyWarEnter"),
                this._pkgMap.AddPkg(t.ID_DsePlotCopyWarMove, "DsePlotCopyWarMove"),
                this._pkgMap.AddPkg(t.ID_DsePlotCopyWarRollStep, "DsePlotCopyWarRollStep"),
                this._pkgMap.AddPkg(t.ID_DseActivateTalent, "DseActivateTalent"),
                this._pkgMap.AddPkg(t.ID_DseTalentList, "DseTalentList"),
                this._pkgMap.AddPkg(t.ID_DseTalentSysFirstFlag, "DseTalentSysFirstFlag"),
                this._pkgMap.AddPkg(t.ID_DseUpgradeTalent, "DseUpgradeTalent"),
                this._pkgMap.AddPkg(t.ID_DsePlotCopyWarOpen, "DsePlotCopyWarOpen"),
                this._pkgMap.AddPkg(t.ID_DseAutoUpgradeScience, "DseAutoUpgradeScience"),
                this._pkgMap.AddPkg(t.ID_DseGlobalArenaBack, "DseGlobalArenaBack"),
                this._pkgMap.AddPkg(t.ID_DseGlobalArenaBattle, "DseGlobalArenaBattle"),
                this._pkgMap.AddPkg(t.ID_DseGlobalArenaBattleProgress, "DseGlobalArenaBattleProgress"),
                this._pkgMap.AddPkg(t.ID_DseGlobalArenaData, "DseGlobalArenaData"),
                this._pkgMap.AddPkg(t.ID_DseGlobalArenaEncourage, "DseGlobalArenaEncourage"),
                this._pkgMap.AddPkg(t.ID_DseGlobalArenaPlayOffList, "DseGlobalArenaPlayOffList"),
                this._pkgMap.AddPkg(t.ID_DseGlobalArenaProstrate, "DseGlobalArenaProstrate"),
                this._pkgMap.AddPkg(t.ID_DseGlobalArenaSelfInfo, "DseGlobalArenaSelfInfo"),
                this._pkgMap.AddPkg(t.ID_DseGlobalArenaUpdateTactic, "DseGlobalArenaUpdateTactic"),
                this._pkgMap.AddPkg(t.ID_DseSignUpAudition, "DseSignUpAudition"),
                this._pkgMap.AddPkg(t.ID_DseSaluteData, "DseSaluteData"),
                this._pkgMap.AddPkg(t.ID_DseSalute, "DseSalute"),
                this._pkgMap.AddPkg(t.ID_DseGoldLeaderExplore, "DseGoldLeaderExplore"),
                this._pkgMap.AddPkg(t.ID_DseGoldLeaderGetOrder, "DseGoldLeaderGetOrder"),
                this._pkgMap.AddPkg(t.ID_DseGoldLeaderInfo, "DseGoldLeaderInfo"),
                this._pkgMap.AddPkg(t.ID_DseGoldLeaderBuyOrder, "DseGoldLeaderBuyOrder"),
                this._pkgMap.AddPkg(t.ID_DseLuckyGodBuyItem, "DseLuckyGodBuyItem"),
                this._pkgMap.AddPkg(t.ID_DseMonthCardData, "DseMonthCardData"),
                this._pkgMap.AddPkg(t.ID_DseGlobalArenaChamption, "DseGlobalArenaChamption"),
                this._pkgMap.AddPkg(t.ID_DseAutoEquipSeikoSoldier, "DseAutoEquipSeikoSoldier"),
                this._pkgMap.AddPkg(t.ID_DseComposeSeiko, "DseComposeSeiko"),
                this._pkgMap.AddPkg(t.ID_DseDecomposeSeiko, "DseDecomposeSeiko"),
                this._pkgMap.AddPkg(t.ID_DseEquipSeiko, "DseEquipSeiko"),
                this._pkgMap.AddPkg(t.ID_DseForgeSeiko, "DseForgeSeiko"),
                this._pkgMap.AddPkg(t.ID_DseReductionSeiko, "DseReductionSeiko"),
                this._pkgMap.AddPkg(t.ID_DseReductionSeikoInfo, "DseReductionSeikoInfo"),
                this._pkgMap.AddPkg(t.ID_DseRemouldSeiko, "DseRemouldSeiko"),
                this._pkgMap.AddPkg(t.ID_DseSeikoList, "DseSeikoList"),
                this._pkgMap.AddPkg(t.ID_DseSeikoPieceList, "DseSeikoPieceList"),
                this._pkgMap.AddPkg(t.ID_DseUnEquipSeiko, "DseUnEquipSeiko"),
                this._pkgMap.AddPkg(t.ID_DseUpdateSeiko, "DseUpdateSeiko"),
                this._pkgMap.AddPkg(t.ID_DseUpgradeSeiko, "DseUpgradeSeiko"),
                this._pkgMap.AddPkg(t.ID_DseSeikoSysFirstFlag, "DseSeikoSysFirstFlag"),
                this._pkgMap.AddPkg(t.ID_DseEnterStageTower, "DseEnterStageTower"),
                this._pkgMap.AddPkg(t.ID_DseSetTacticForStageTower, "DseSetTacticForStageTower"),
                this._pkgMap.AddPkg(t.ID_DseStageTowerData, "DseStageTowerData"),
                this._pkgMap.AddPkg(t.ID_DseGetTacticForStageTower, "DseGetTacticForStageTower"),
                this._pkgMap.AddPkg(t.ID_DseUpdateEnemyForStageTower, "DseUpdateEnemyForStageTower"),
                this._pkgMap.AddPkg(t.ID_DseStageTowerPurchaseAndResurr, "DseStageTowerPurchaseAndResurr"),
                this._pkgMap.AddPkg(t.ID_DseFindEnemyForStageTower, "DseFindEnemyForStageTower"),
                this._pkgMap.AddPkg(t.ID_DseSeikoShopData, "DseSeikoShopData"),
                this._pkgMap.AddPkg(t.ID_DseSeikoShopHandle, "DseSeikoShopHandle"),
                this._pkgMap.AddPkg(t.ID_DseOnearmedBanditTen, "DseOnearmedBanditTen"),
                this._pkgMap.AddPkg(t.ID_DsePaperLockOperation, "DsePaperLockOperation"),
                this._pkgMap.AddPkg(t.ID_DseShipLockOperation, "DseShipLockOperation"),
                this._pkgMap.AddPkg(t.ID_DseCaptainLockOpt, "DseCaptainLockOpt"),
                this._pkgMap.AddPkg(t.ID_DseRenameGuild, "DseRenameGuild"),
                this._pkgMap.AddPkg(t.ID_DseSeikoLockOpt, "DseSeikoLockOpt"),
                this._pkgMap.AddPkg(t.ID_DseSoulLockOpt, "DseSoulLockOpt"),
                this._pkgMap.AddPkg(t.ID_DsePartsLockOpt, "DsePartsLockOpt"),
                this._pkgMap.AddPkg(t.ID_DseGoldIslandCancelHelped, "DseGoldIslandCancelHelped"),
                this._pkgMap.AddPkg(t.ID_DseGlobalArenaCheckEncourage, "DseGlobalArenaCheckEncourage"),
                this._pkgMap.AddPkg(t.ID_DseGuildBattleAuto, "DseGuildBattleAuto"),
                this._pkgMap.AddPkg(t.ID_DseTuanGouInfo, "DseTuanGouInfo"),
                this._pkgMap.AddPkg(t.ID_DseTuanGouOpt, "DseTuanGouOpt"),
                this._pkgMap.AddPkg(t.ID_DseStageTowerAcityData, "DseStageTowerAcityData"),
                this._pkgMap.AddPkg(t.ID_DseStageTowerAcityHandle, "DseStageTowerAcityHandle"),
                this._pkgMap.AddPkg(t.ID_DseSeiKoExchange, "DseSeiKoExchange"),
                this._pkgMap.AddPkg(t.ID_DseSeiKoExchangeDataSync, "DseSeiKoExchangeDataSync"),
                this._pkgMap.AddPkg(t.ID_DseSeiKoScore, "DseSeiKoScore"),
                this._pkgMap.AddPkg(t.ID_DseWeal, "DseWeal"),
                this._pkgMap.AddPkg(t.ID_DseRechargeBackGift, "DseRechargeBackGift"),
                this._pkgMap.AddPkg(t.ID_DseRechargeBackGiftData, "DseRechargeBackGiftData"),
                this._pkgMap.AddPkg(t.ID_DseRechargeBackGiftEnter, "DseRechargeBackGiftEnter"),
                this._pkgMap.AddPkg(t.ID_DseCenterCampBattleCampRank, "DseCenterCampBattleCampRank"),
                this._pkgMap.AddPkg(t.ID_DseUseSoulGift, "DseUseSoulGift"),
                this._pkgMap.AddPkg(t.ID_DseAutoEquipSoul, "DseAutoEquipSoul"),
                this._pkgMap.AddPkg(t.ID_DseUnAutoEquipSoul, "DseUnAutoEquipSoul"),
                this._pkgMap.AddPkg(t.ID_DseGlobalGuildBattleSign, "DseGlobalGuildBattleSign"),
                this._pkgMap.AddPkg(t.ID_DseGlobalGuildBattleAdjust, "DseGlobalGuildBattleAdjust"),
                this._pkgMap.AddPkg(t.ID_DseGlobalGuildBattleEncourage, "DseGlobalGuildBattleEncourage"),
                this._pkgMap.AddPkg(t.ID_DseGlobalGuildBattleUpdate, "DseGlobalGuildBattleUpdate"),
                this._pkgMap.AddPkg(t.ID_DseGlobalGuildBattleData, "DseGlobalGuildBattleData"),
                this._pkgMap.AddPkg(t.ID_DseGlobalGuildBattleSeeMember, "DseGlobalGuildBattleSeeMember"),
                this._pkgMap.AddPkg(t.ID_DseGlobalGuildBattleProstrate, "DseGlobalGuildBattleProstrate"),
                this._pkgMap.AddPkg(t.ID_DseGlobalGuildBattleGuildGroupVs, "DseGlobalGuildBattleGuildGroupVs"),
                this._pkgMap.AddPkg(t.ID_DseGlobalGuildBattleGuildVs, "DseGlobalGuildBattleGuildVs"),
                this._pkgMap.AddPkg(t.ID_DseGlobalGuildBattleVsBattle, "DseGlobalGuildBattleVsBattle"),
                this._pkgMap.AddPkg(t.ID_DseScoutGuild, "DseScoutGuild"),
                this._pkgMap.AddPkg(t.ID_DseGlobalGuildBattleChamptionMember, "DseGlobalGuildBattleChamptionMember"),
                this._pkgMap.AddPkg(t.ID_DseGlobalGuildBattleChamptionList, "DseGlobalGuildBattleChamptionList"),
                this._pkgMap.AddPkg(t.ID_DseOnLineTime, "DseOnLineTime"),
                this._pkgMap.AddPkg(t.ID_DseActivityWebData, "DseActivityWebData"),
                this._pkgMap.AddPkg(t.ID_DceGuideSave, "DceGuideSave"),
                this._pkgMap.AddPkg(t.ID_DseFocusAward, "DseFocusAward"),
                this._pkgMap.AddPkg(t.ID_DseRechargeInfo, "DseRechargeInfo"),
                this._pkgMap.AddPkg(t.ID_DseExchangeCode, "DseExchangeCode")
        },
        t.ID_DseAccBind = 512,
        t.ID_DseActiveTips = 513,
        t.ID_DseActivity = 514,
        t.ID_DseActivityData = 515,
        t.ID_DseAddFriend = 516,
        t.ID_DseAddMail = 517,
        t.ID_DseAddOwnedPaper = 518,
        t.ID_DseAddParts = 519,
        t.ID_DseAddShip = 520,
        t.ID_DseAllLastID = 521,
        t.ID_DseApplyList = 522,
        t.ID_DseArenaData = 523,
        t.ID_DseArenaExchange = 524,
        t.ID_DseArenaList = 525,
        t.ID_DseAuthState = 526,
        t.ID_DseAutoEquipSoldier = 527,
        t.ID_DseAwardCenter = 528,
        t.ID_DseBattleInfo = 529,
        t.ID_DseBattleReview = 530,
        t.ID_DseBattleStart = 531,
        t.ID_DseBattleStartBySweep = 532,
        t.ID_DseBlackList = 533,
        t.ID_DseBlackListOpt = 534,
        t.ID_DseBroadcast = 535,
        t.ID_DseBuy = 536,
        t.ID_DseBuyGuard = 537,
        t.ID_DseBuyOil = 538,
        t.ID_DseCampBattleData = 539,
        t.ID_DseCampBattleMove = 540,
        t.ID_DseCampBattleMsg = 541,
        t.ID_DseCampBattleResult = 542,
        t.ID_DseChargePaper = 543,
        t.ID_DseChat = 544,
        t.ID_DseChatData = 545,
        t.ID_DseChatMsg = 546,
        t.ID_DseChatMsgLog = 547,
        t.ID_DseCheckPlayerName = 548,
        t.ID_DseChristmasMineral = 549,
        t.ID_DseChristmasMineralStart = 550,
        t.ID_DseChristmasScroeExchange = 551,
        t.ID_DseChritmasLogin = 552,
        t.ID_DseChritmasLottery = 553,
        t.ID_DseChritmasLotteryDropList = 554,
        t.ID_DseChritmasLotteryStart = 555,
        t.ID_DseClearCampBattleCD = 556,
        t.ID_DseComposeParts = 557,
        t.ID_DseConsumeExchange = 558,
        t.ID_DseConsumeExchangeData = 559,
        t.ID_DseCreateGuild = 560,
        t.ID_DseCreateShip = 561,
        t.ID_DseDayLimitFightData = 562,
        t.ID_DseDecomposeParts = 563,
        t.ID_DseDeleteFriend = 564,
        t.ID_DseDelParts = 565,
        t.ID_DseDelShip = 566,
        t.ID_DseDrawAllElectric = 567,
        t.ID_DseDrawElectric = 568,
        t.ID_DseEnterArena = 569,
        t.ID_DseEnterCampBattle = 570,
        t.ID_DseEnterGuard = 571,
        t.ID_DseEquipParts = 572,
        t.ID_DseEquipSoul = 573,
        t.ID_DseFriendList = 574,
        t.ID_DseFuncSwich = 575,
        t.ID_DseGetAward = 576,
        t.ID_DseGetCenterGold = 577,
        t.ID_DseGetDayLimitFight = 578,
        t.ID_DseGetGuardRank = 579,
        t.ID_DseGetMailProp = 580,
        t.ID_DseGetMedal = 581,
        t.ID_DseGetTactic = 582,
        t.ID_DseGetWeakCamp = 583,
        t.ID_DseGhostShip = 584,
        t.ID_DseGhostShipData = 585,
        t.ID_DseGuardStage = 586,
        t.ID_DseGuildApply = 587,
        t.ID_DseGuildApplyList = 588,
        t.ID_DseGuildApproval = 589,
        t.ID_DseGuildBuyGift = 590,
        t.ID_DseGuildCancelApply = 591,
        t.ID_DseGuildData = 592,
        t.ID_DseGuildDemise = 593,
        t.ID_DseGuildDismiss = 594,
        t.ID_DseGuildDismissCancel = 595,
        t.ID_DseGuildDonate = 596,
        t.ID_DseGuildExpel = 597,
        t.ID_DseGuildFireDeputy = 598,
        t.ID_DseGuildInvite = 599,
        t.ID_DseGuildList = 600,
        t.ID_DseGuildMemberList = 601,
        t.ID_DseGuildQuit = 602,
        t.ID_DseGuildSetDeputy = 603,
        t.ID_DseGuildSetMedal = 604,
        t.ID_DseGuildUpgrade = 605,
        t.ID_DseHeartbeat = 606,
        t.ID_DseInvitedList = 607,
        t.ID_DseInviteFriend = 608,
        t.ID_DseLimitShip = 609,
        t.ID_DseLimitShipData = 610,
        t.ID_DseLuckyGoddessData = 611,
        t.ID_DseLuckyGoddessForCharge = 612,
        t.ID_DseLuckyGoddessForFree = 613,
        t.ID_DseLuckyWheelActivity = 614,
        t.ID_DseLuckyWheelActivityData = 615,
        t.ID_DseMailList = 616,
        t.ID_DseMedalData = 617,
        t.ID_DseMilitaryRankGetDailyReward = 618,
        t.ID_DseMilitaryRankInfo = 619,
        t.ID_DseMilitaryRankUpgrad = 620,
        t.ID_DseMisteryShopRefresh = 621,
        t.ID_DseModifyDeclaration = 622,
        t.ID_DseModifyNotify = 623,
        t.ID_DseMonthCard = 624,
        t.ID_DseMonthSignTake = 625,
        t.ID_DseNewDay = 626,
        t.ID_DseOwnedPaper = 627,
        t.ID_DseOwnedPaperFirstFlag = 628,
        t.ID_DsePaperChargeCount = 629,
        t.ID_DsePaperList = 630,
        t.ID_DsePaperPieceList = 631,
        t.ID_DsePartPieceList = 632,
        t.ID_DsePartsList = 633,
        t.ID_DsePropList = 634,
        t.ID_DseQuestionAnswer = 635,
        t.ID_DseQuestionList = 636,
        t.ID_DseQuestionRank = 637,
        t.ID_DseRankList = 638,
        t.ID_DseRecElectricList = 639,
        t.ID_DseRecommandInviteList = 640,
        t.ID_DseRefuseAddFriend = 641,
        t.ID_DseRemouldParts = 642,
        t.ID_DseRemouldShip = 643,
        t.ID_DseRenameRole = 644,
        t.ID_DseRenameShip = 645,
        t.ID_DseResetGuard = 646,
        t.ID_DseResetStageCount = 647,
        t.ID_DseRetireShip = 648,
        t.ID_DseRobberyList = 649,
        t.ID_DseSalePaper = 650,
        t.ID_DseScienceList = 651,
        t.ID_DseScoutSoldier = 652,
        t.ID_DseSearchGuild = 653,
        t.ID_DseSearchPlayer = 654,
        t.ID_DseSellProp = 655,
        t.ID_DseSendElectric = 656,
        t.ID_DseSendMail = 657,
        t.ID_DseSetCaption = 658,
        t.ID_DseSetRole = 659,
        t.ID_DseSetSoldier = 660,
        t.ID_DseSetTactic = 661,
        t.ID_DseSetVerifyOptions = 662,
        t.ID_DseSevenDaysExchange = 663,
        t.ID_DseSevenDaysExchangeData = 664,
        t.ID_DseShipList = 665,
        t.ID_DseShopData = 666,
        t.ID_DseSoldierList = 667,
        t.ID_DseSoul = 668,
        t.ID_DseSoulEat = 669,
        t.ID_DseSoulList = 670,
        t.ID_DseSpy = 671,
        t.ID_DseSpyData = 672,
        t.ID_DseStageData = 673,
        t.ID_DseStageList = 674,
        t.ID_DseStartServerActivity = 675,
        t.ID_DseTrain = 676,
        t.ID_DseUnEquipParts = 677,
        t.ID_DseUnEquipSoul = 678,
        t.ID_DseUpdateMail = 679,
        t.ID_DseUpdateParts = 680,
        t.ID_DseUpdateShip = 681,
        t.ID_DseUpgradeBuild = 682,
        t.ID_DseUpgradeParts = 683,
        t.ID_DseUpgradeScience = 684,
        t.ID_DseUpgradeShip = 685,
        t.ID_DseUpgradeSkill = 686,
        t.ID_DseUseProp = 687,
        t.ID_DseUserComeBack = 688,
        t.ID_DseUserComeBackReward = 689,
        t.ID_DseUserData = 690,
        t.ID_DseGoddessReward = 691,
        t.ID_DseGoddessRewardData = 692,
        t.ID_DseLuckyCatDataRequest = 693,
        t.ID_DseLuckyCatRequest = 694,
        t.ID_DseLuckBoxPointExchange = 695,
        t.ID_DseLuckBoxPointExchangeOpen = 696,
        t.ID_DseLoginPokerOpen = 697,
        t.ID_DseLoginPokerAction = 698,
        t.ID_DseLoginPokerFinal = 699,
        t.ID_DseReductionParts = 700,
        t.ID_DseBonusFlyDataRequest = 701,
        t.ID_DseBonusFlyRequest = 702,
        t.ID_DseRechargeSevenDayRequest = 703,
        t.ID_DseRechargeSevenDayRequestData = 704,
        t.ID_DseCenterCampBattleData = 705,
        t.ID_DseCenterCampBattleMove = 706,
        t.ID_DseCenterCampBattleMsg = 707,
        t.ID_DseCenterCampBattleResult = 708,
        t.ID_DseClearCenterCampBattleCD = 709,
        t.ID_DseEnterCenterCampBattle = 710,
        t.ID_DseReductionPartsInfo = 711,
        t.ID_DseUsePaperPieceGift = 712,
        t.ID_DseOnearmedBanditDataRequest = 713,
        t.ID_DseOnearmedBanditRequest = 714,
        t.ID_DseValentineDataRequest = 715,
        t.ID_DseValentineGiveGift = 716,
        t.ID_DseCampBattleBuy = 717,
        t.ID_DseCenterCampBattleBuy = 718,
        t.ID_DseAddSoulOwnedPaper = 719,
        t.ID_DseOwnedSoulPaperFirstFlag = 720,
        t.ID_DseLuckyGoddnessForCharge = 721,
        t.ID_DseShipFormationInfo = 722,
        t.ID_DseShipFormationLevelUp = 723,
        t.ID_DseShipFormationStarUp = 724,
        t.ID_DseShipFormationAddNotice = 725,
        t.ID_DseShipFormationChoose = 726,
        t.ID_DseShipFormationFistFlag = 727,
        t.ID_DseRegSecondDayGift = 728,
        t.ID_DseBuySpyItem = 729,
        t.ID_DseChallengeDataRequest = 730,
        t.ID_DseChallengeSignUp = 731,
        t.ID_DseChallengeFight = 732,
        t.ID_DseChallengeAction = 733,
        t.ID_DseChallengeEnemyData = 734,
        t.ID_DseChallengeRevenge = 735,
        t.ID_DseChallengeRefresh = 736,
        t.ID_DseChallengeRank = 737,
        t.ID_DseChallengeChampion = 738,
        t.ID_DseChallengeWorship = 739,
        t.ID_DseChallengeBuy = 740,
        t.ID_DseChallengeRefreshCharge = 741,
        t.ID_DseBuyRecruitItem = 742,
        t.ID_DseCaptainData = 743,
        t.ID_DseCaptainList = 744,
        t.ID_DseCaptainPieceList = 745,
        t.ID_DseComposeCaptain = 746,
        t.ID_DseEquipCaptain = 747,
        t.ID_DseExchangeCaptain = 748,
        t.ID_DseFireCaptain = 749,
        t.ID_DseLimitCaptain = 750,
        t.ID_DseLimitCaptainData = 751,
        t.ID_DsePromoteCaptain = 752,
        t.ID_DseRecruitCaptain = 753,
        t.ID_DseUpdateCaptain = 754,
        t.ID_DseUpgradeCaptain = 755,
        t.ID_DseCaptainFirstFlag = 756,
        t.ID_DseChallengeLogin = 757,
        t.ID_DseUseSuperCaptainGift = 758,
        t.ID_DseLimitShipBuyItem = 759,
        t.ID_DseBuyLimitCaptain = 760,
        t.ID_DseBuyGhostShip = 761,
        t.ID_DseCampBattleSetTrustee = 762,
        t.ID_DseCaptainPaperAdd = 763,
        t.ID_DseCaptainPaperFirstFlag = 764,
        t.ID_DseMedalPromote = 765,
        t.ID_DseSoulDecompose = 766,
        t.ID_DseSoulRestore = 767,
        t.ID_DseSuperExchangeInfo = 768,
        t.ID_DseSuperExchangeItem = 769,
        t.ID_DseGuildScienceList = 770,
        t.ID_DseUpgradeGuildScience = 771,
        t.ID_DseClearGuildBattleCD = 772,
        t.ID_DseGuildBattleBuy = 773,
        t.ID_DseGuildBattleData = 774,
        t.ID_DseGuildBattleEnter = 775,
        t.ID_DseGuildBattleMove = 776,
        t.ID_DseGuildBattleMsg = 777,
        t.ID_DseGuildBattlePrepare = 778,
        t.ID_DseGuildBattleRankList = 779,
        t.ID_DseGuildBattleResult = 780,
        t.ID_DseGuildBattleSignUp = 781,
        t.ID_DseGuildBattleSignUpList = 782,
        t.ID_DseGoldIslandOpen = 783,
        t.ID_DseGoldIslandSearch = 784,
        t.ID_DseGoldIslandOccupy = 785,
        t.ID_DseGoldIslandHelp = 786,
        t.ID_DseGoldIslandInviteHelp = 787,
        t.ID_DseGoldIslandDelayTime = 788,
        t.ID_DseGoldIslandInviteMemberlist = 789,
        t.ID_DseGoldIslandAgreeApply = 790,
        t.ID_DseGoldIslandApplyHelp = 791,
        t.ID_DseGoldIslandCancel = 792,
        t.ID_DseChangeRole = 793,
        t.ID_DseArmadaData = 794,
        t.ID_DseLimitTimeShopBuy = 795,
        t.ID_DseLimitTimeShopInfo = 796,
        t.ID_DseComposeSouls = 797,
        t.ID_DseSoulPieceList = 798,
        t.ID_DseGetTaskReward = 799,
        t.ID_DseTaskRewardData = 800,
        t.ID_DseExchangeCaptainCount = 801,
        t.ID_DsePlotCopyWarBattleInfo = 802,
        t.ID_DsePlotCopyWarData = 803,
        t.ID_DsePlotCopyWarEnter = 804,
        t.ID_DsePlotCopyWarMove = 805,
        t.ID_DsePlotCopyWarRollStep = 806,
        t.ID_DseActivateTalent = 807,
        t.ID_DseTalentList = 808,
        t.ID_DseTalentSysFirstFlag = 809,
        t.ID_DseUpgradeTalent = 810,
        t.ID_DsePlotCopyWarOpen = 811,
        t.ID_DseAutoUpgradeScience = 812,
        t.ID_DseGlobalArenaBack = 813,
        t.ID_DseGlobalArenaBattle = 814,
        t.ID_DseGlobalArenaBattleProgress = 815,
        t.ID_DseGlobalArenaData = 816,
        t.ID_DseGlobalArenaEncourage = 817,
        t.ID_DseGlobalArenaPlayOffList = 818,
        t.ID_DseGlobalArenaProstrate = 819,
        t.ID_DseGlobalArenaSelfInfo = 820,
        t.ID_DseGlobalArenaUpdateTactic = 821,
        t.ID_DseSignUpAudition = 822,
        t.ID_DseSaluteData = 823,
        t.ID_DseSalute = 824,
        t.ID_DseGoldLeaderExplore = 825,
        t.ID_DseGoldLeaderGetOrder = 826,
        t.ID_DseGoldLeaderInfo = 827,
        t.ID_DseGoldLeaderBuyOrder = 828,
        t.ID_DseLuckyGodBuyItem = 829,
        t.ID_DseMonthCardData = 830,
        t.ID_DseGlobalArenaChamption = 831,
        t.ID_DseAutoEquipSeikoSoldier = 832,
        t.ID_DseComposeSeiko = 833,
        t.ID_DseDecomposeSeiko = 834,
        t.ID_DseEquipSeiko = 835,
        t.ID_DseForgeSeiko = 836,
        t.ID_DseReductionSeiko = 837,
        t.ID_DseReductionSeikoInfo = 838,
        t.ID_DseRemouldSeiko = 839,
        t.ID_DseSeikoList = 840,
        t.ID_DseSeikoPieceList = 841,
        t.ID_DseUnEquipSeiko = 842,
        t.ID_DseUpdateSeiko = 843,
        t.ID_DseUpgradeSeiko = 844,
        t.ID_DseSeikoSysFirstFlag = 845,
        t.ID_DseEnterStageTower = 846,
        t.ID_DseSetTacticForStageTower = 847,
        t.ID_DseStageTowerData = 848,
        t.ID_DseGetTacticForStageTower = 849,
        t.ID_DseUpdateEnemyForStageTower = 850,
        t.ID_DseStageTowerPurchaseAndResurr = 851,
        t.ID_DseFindEnemyForStageTower = 852,
        t.ID_DseSeikoShopData = 853,
        t.ID_DseSeikoShopHandle = 854,
        t.ID_DseOnearmedBanditTen = 855,
        t.ID_DsePaperLockOperation = 856,
        t.ID_DseShipLockOperation = 857,
        t.ID_DseCaptainLockOpt = 858,
        t.ID_DseRenameGuild = 859,
        t.ID_DseSeikoLockOpt = 860,
        t.ID_DseSoulLockOpt = 861,
        t.ID_DsePartsLockOpt = 862,
        t.ID_DseGoldIslandCancelHelped = 863,
        t.ID_DseGlobalArenaCheckEncourage = 864,
        t.ID_DseGuildBattleAuto = 865,
        t.ID_DseTuanGouInfo = 866,
        t.ID_DseTuanGouOpt = 867,
        t.ID_DseStageTowerAcityData = 868,
        t.ID_DseStageTowerAcityHandle = 869,
        t.ID_DseSeiKoExchange = 870,
        t.ID_DseSeiKoExchangeDataSync = 871,
        t.ID_DseSeiKoScore = 872,
        t.ID_DseWeal = 873,
        t.ID_DseRechargeBackGift = 874,
        t.ID_DseRechargeBackGiftData = 875,
        t.ID_DseRechargeBackGiftEnter = 876,
        t.ID_DseCenterCampBattleCampRank = 877,
        t.ID_DseUseSoulGift = 878,
        t.ID_DseAutoEquipSoul = 879,
        t.ID_DseUnAutoEquipSoul = 880,
        t.ID_DseGlobalGuildBattleSign = 881,
        t.ID_DseGlobalGuildBattleAdjust = 882,
        t.ID_DseGlobalGuildBattleEncourage = 883,
        t.ID_DseGlobalGuildBattleUpdate = 884,
        t.ID_DseGlobalGuildBattleData = 885,
        t.ID_DseGlobalGuildBattleSeeMember = 886,
        t.ID_DseGlobalGuildBattleProstrate = 887,
        t.ID_DseGlobalGuildBattleGuildGroupVs = 888,
        t.ID_DseGlobalGuildBattleGuildVs = 889,
        t.ID_DseGlobalGuildBattleVsBattle = 890,
        t.ID_DseScoutGuild = 891,
        t.ID_DseGlobalGuildBattleChamptionMember = 892,
        t.ID_DseGlobalGuildBattleChamptionList = 893,
        t.ID_DseActivityWebData = 894,
        t.ID_DseOnLineTime = 895,
        t.ID_DseFocusAward = 896,
        t.ID_DseRechargeInfo = 897,
        t.ID_DseExchangeCode = 898,
        t.ID_DceAccBind = 1024,
        t.ID_DceActivity = 1025,
        t.ID_DceActivityData = 1026,
        t.ID_DceAddFriend = 1027,
        t.ID_DceAllLastID = 1028,
        t.ID_DceApplyList = 1029,
        t.ID_DceArenaExchange = 1030,
        t.ID_DceAutoEquipSoldier = 1031,
        t.ID_DceAwardCenter = 1032,
        t.ID_DceBattleReview = 1033,
        t.ID_DceBattleStart = 1034,
        t.ID_DceBlackList = 1035,
        t.ID_DceBlackListOpt = 1036,
        t.ID_DceBuy = 1037,
        t.ID_DceBuyGuard = 1038,
        t.ID_DceBuyOil = 1039,
        t.ID_DceCampBattleData = 1040,
        t.ID_DceCampBattleMove = 1041,
        t.ID_DceCampBattleResult = 1042,
        t.ID_DceCenterRecovery = 1043,
        t.ID_DceChargePaper = 1044,
        t.ID_DceChat = 1045,
        t.ID_DceChatData = 1046,
        t.ID_DceCheckPlayerName = 1047,
        t.ID_DceChristmasMineral = 1048,
        t.ID_DceChristmasMineralStart = 1049,
        t.ID_DceChristmasScroeExchange = 1050,
        t.ID_DceChritmasLottery = 1051,
        t.ID_DceChritmasLotteryStart = 1052,
        t.ID_DceClearCampBattleCD = 1053,
        t.ID_DceComposeParts = 1054,
        t.ID_DceConsumeExchange = 1055,
        t.ID_DceConsumeExchangeData = 1056,
        t.ID_DceCreateGuild = 1057,
        t.ID_DceCreateShip = 1058,
        t.ID_DceDayLimitFightData = 1059,
        t.ID_DceDecomposeParts = 1060,
        t.ID_DceDeleteFriend = 1061,
        t.ID_DceDrawAllElectric = 1062,
        t.ID_DceDrawElectric = 1063,
        t.ID_DceEnterArena = 1064,
        t.ID_DceEnterCampBattle = 1065,
        t.ID_DceEnterGuard = 1066,
        t.ID_DceEquipParts = 1067,
        t.ID_DceEquipSoul = 1068,
        t.ID_DceFriendList = 1069,
        t.ID_DceGetAward = 1070,
        t.ID_DceGetCenterGold = 1071,
        t.ID_DceGetDayLimitFight = 1072,
        t.ID_DceGetGuardRank = 1073,
        t.ID_DceGetMailProp = 1074,
        t.ID_DceGetMedal = 1075,
        t.ID_DceGetTactic = 1076,
        t.ID_DceGetWeakCamp = 1077,
        t.ID_DceGhostShip = 1078,
        t.ID_DceGhostShipData = 1079,
        t.ID_DceGuardStage = 1080,
        t.ID_DceGuideStep = 1081,
        t.ID_DceGuildApply = 1082,
        t.ID_DceGuildApplyList = 1083,
        t.ID_DceGuildApproval = 1084,
        t.ID_DceGuildBuyGift = 1085,
        t.ID_DceGuildCancelApply = 1086,
        t.ID_DceGuildData = 1087,
        t.ID_DceGuildDemise = 1088,
        t.ID_DceGuildDismiss = 1089,
        t.ID_DceGuildDismissCancel = 1090,
        t.ID_DceGuildDonate = 1091,
        t.ID_DceGuildExpel = 1092,
        t.ID_DceGuildFireDeputy = 1093,
        t.ID_DceGuildInvite = 1094,
        t.ID_DceGuildList = 1095,
        t.ID_DceGuildMemberList = 1096,
        t.ID_DceGuildQuit = 1097,
        t.ID_DceGuildSetDeputy = 1098,
        t.ID_DceGuildSetMedal = 1099,
        t.ID_DceGuildUpgrade = 1100,
        t.ID_DceHeartbeat = 1101,
        t.ID_DceInvitedList = 1102,
        t.ID_DceInviteFriend = 1103,
        t.ID_DceLimitShip = 1104,
        t.ID_DceLimitShipData = 1105,
        t.ID_DceLuckyGoddessData = 1106,
        t.ID_DceLuckyGoddessForFree = 1107,
        t.ID_DceLuckyWheelActivity = 1108,
        t.ID_DceLuckyWheelActivityData = 1109,
        t.ID_DceMailList = 1110,
        t.ID_DceMedalData = 1111,
        t.ID_DceMilitaryRankGetDailyReward = 1112,
        t.ID_DceMilitaryRankInfo = 1113,
        t.ID_DceMilitaryRankUpgrad = 1114,
        t.ID_DceMisteryShopRefresh = 1115,
        t.ID_DceModifyDeclaration = 1116,
        t.ID_DceModifyNotify = 1117,
        t.ID_DceMonthCard = 1118,
        t.ID_DceMonthSignTake = 1119,
        t.ID_DceNewDay = 1120,
        t.ID_DceOwnedPaper = 1121,
        t.ID_DcePaperChargeCount = 1122,
        t.ID_DcePaperList = 1123,
        t.ID_DcePaperPieceList = 1124,
        t.ID_DcePartPieceList = 1125,
        t.ID_DcePartsList = 1126,
        t.ID_DcePropList = 1127,
        t.ID_DceQuestionAnswer = 1128,
        t.ID_DceQuestionList = 1129,
        t.ID_DceQuestionRank = 1130,
        t.ID_DceRankList = 1131,
        t.ID_DceRecElectricList = 1132,
        t.ID_DceRecommandInviteList = 1133,
        t.ID_DceRefuseAddFriend = 1134,
        t.ID_DceRemouldParts = 1135,
        t.ID_DceRemouldShip = 1136,
        t.ID_DceRenameRole = 1137,
        t.ID_DceRenameShip = 1138,
        t.ID_DceResetGuard = 1139,
        t.ID_DceResetStageCount = 1140,
        t.ID_DceRetireShip = 1141,
        t.ID_DceRobberyList = 1142,
        t.ID_DceSalePaper = 1143,
        t.ID_DceSaveTrain = 1144,
        t.ID_DceScienceList = 1145,
        t.ID_DceScoutSoldier = 1146,
        t.ID_DceSearchGuild = 1147,
        t.ID_DceSearchPlayer = 1148,
        t.ID_DceSellProp = 1149,
        t.ID_DceSendElectric = 1150,
        t.ID_DceSendMail = 1151,
        t.ID_DceSetCaption = 1152,
        t.ID_DceSetRole = 1153,
        t.ID_DceSetSoldier = 1154,
        t.ID_DceSetTactic = 1155,
        t.ID_DceSetVerifyOptions = 1156,
        t.ID_DceSevenDaysExchange = 1157,
        t.ID_DceSevenDaysExchangeData = 1158,
        t.ID_DceShipList = 1159,
        t.ID_DceShopData = 1160,
        t.ID_DceSoldierList = 1161,
        t.ID_DceSoul = 1162,
        t.ID_DceSoulEat = 1163,
        t.ID_DceSoulList = 1164,
        t.ID_DceSpy = 1165,
        t.ID_DceSpyData = 1166,
        t.ID_DceStageList = 1167,
        t.ID_DceTrain = 1168,
        t.ID_DceUnEquipParts = 1169,
        t.ID_DceUnEquipSoul = 1170,
        t.ID_DceUpdateElectric = 1171,
        t.ID_DceUpdateOil = 1172,
        t.ID_DceUpgradeBuild = 1173,
        t.ID_DceUpgradeParts = 1174,
        t.ID_DceUpgradeScience = 1175,
        t.ID_DceUpgradeShip = 1176,
        t.ID_DceUpgradeSkill = 1177,
        t.ID_DceUseProp = 1178,
        t.ID_DceUserComeBackReward = 1179,
        t.ID_DceUserData = 1180,
        t.ID_DceGoddessReward = 1181,
        t.ID_DceGoddessRewardData = 1182,
        t.ID_DceLuckyCatDataRequest = 1183,
        t.ID_DceLuckyCatRequest = 1184,
        t.ID_DceLuckBoxPointExchange = 1185,
        t.ID_DceLuckBoxPointExchangeOpen = 1186,
        t.ID_DceLoginPokerOpen = 1187,
        t.ID_DceLoginPokerAction = 1188,
        t.ID_DceLoginPokerFinal = 1189,
        t.ID_DceReductionParts = 1190,
        t.ID_DceBonusFlyDataRequest = 1191,
        t.ID_DceBonusFlyRequest = 1192,
        t.ID_DceRechargeSevenDayRequest = 1193,
        t.ID_DceRechargeSevenDayRequestData = 1194,
        t.ID_DceEnterCenterCampBattle = 1195,
        t.ID_DceCenterCampBattleData = 1196,
        t.ID_DceCenterCampBattleMove = 1197,
        t.ID_DceCenterCampBattleResult = 1198,
        t.ID_DceClearCenterCampBattleCD = 1199,
        t.ID_DceCenterCampBattleRankList = 1200,
        t.ID_DceReductionPartsInfo = 1201,
        t.ID_DceUsePaperPieceGift = 1202,
        t.ID_DceOnearmedBanditDataRequest = 1203,
        t.ID_DceOnearmedBanditRequest = 1204,
        t.ID_DceValentineDataRequest = 1205,
        t.ID_DceValentineGiveGift = 1206,
        t.ID_DceCampBattleBuy = 1207,
        t.ID_DceCenterCampBattleBuy = 1208,
        t.ID_DceLuckyGoddnessForCharge = 1209,
        t.ID_DceShipFormationInfo = 1210,
        t.ID_DceShipFormationLevelUp = 1211,
        t.ID_DceShipFormationChoose = 1212,
        t.ID_DceRegSecondDayGift = 1213,
        t.ID_DceBuySpyItem = 1214,
        t.ID_DceChallengeDataRequest = 1215,
        t.ID_DceChallengeSignUp = 1216,
        t.ID_DceChallengeFight = 1217,
        t.ID_DceChallengeAction = 1218,
        t.ID_DceChallengeEnemyData = 1219,
        t.ID_DceChallengeRevenge = 1220,
        t.ID_DceChallengeRefresh = 1221,
        t.ID_DceChallengeRank = 1222,
        t.ID_DceChallengeChampion = 1223,
        t.ID_DceChallengeWorship = 1224,
        t.ID_DceChallengeBuy = 1225,
        t.ID_DceChallengeRefreshCharge = 1226,
        t.ID_DceBuyRecruitItem = 1227,
        t.ID_DceCaptainData = 1228,
        t.ID_DceCaptainList = 1229,
        t.ID_DceCaptainPieceList = 1230,
        t.ID_DceComposeCaptain = 1231,
        t.ID_DceEquipCaptain = 1232,
        t.ID_DceExchangeCaptain = 1233,
        t.ID_DceFireCaptain = 1234,
        t.ID_DceLimitCaptain = 1235,
        t.ID_DceLimitCaptainData = 1236,
        t.ID_DcePromoteCaptain = 1237,
        t.ID_DceRecruitCaptain = 1238,
        t.ID_DceUpgradeCaptain = 1239,
        t.ID_DceUseSuperCaptainGift = 1240,
        t.ID_DceLimitShipBuyItem = 1241,
        t.ID_DceBuyLimitCaptain = 1242,
        t.ID_DceBuyGhostShip = 1243,
        t.ID_DceCampBattleSetTrustee = 1244,
        t.ID_DceMedalPromote = 1245,
        t.ID_DceSoulDecompose = 1246,
        t.ID_DceSoulRestore = 1247,
        t.ID_DceSuperExchangeInfo = 1248,
        t.ID_DceSuperExchangeItem = 1249,
        t.ID_DceGuildScienceList = 1250,
        t.ID_DceUpgradeGuildScience = 1251,
        t.ID_DceClearGuildBattleCD = 1252,
        t.ID_DceGuildBattleBuy = 1253,
        t.ID_DceGuildBattleData = 1254,
        t.ID_DceGuildBattleEnter = 1255,
        t.ID_DceGuildBattleMove = 1256,
        t.ID_DceGuildBattlePrepare = 1257,
        t.ID_DceGuildBattleRankList = 1258,
        t.ID_DceGuildBattleResult = 1259,
        t.ID_DceGuildBattleSignUp = 1260,
        t.ID_DceGuildBattleSignUpList = 1261,
        t.ID_DceGoldIslandOpen = 1262,
        t.ID_DceGoldIslandSearch = 1263,
        t.ID_DceGoldIslandOccupy = 1264,
        t.ID_DceGoldIslandHelp = 1265,
        t.ID_DceGoldIslandInviteHelp = 1266,
        t.ID_DceGoldIslandDelayTime = 1267,
        t.ID_DceGoldIslandInviteMemberlist = 1268,
        t.ID_DceGoldIslandAgreeApply = 1269,
        t.ID_DceGoldIslandApplyHelp = 1270,
        t.ID_DceGoldIslandCancel = 1271,
        t.ID_DceChangeRole = 1272,
        t.ID_DceArmadaData = 1273,
        t.ID_DceLimitTimeShopBuy = 1274,
        t.ID_DceLimitTimeShopInfo = 1275,
        t.ID_DceComposeSouls = 1276,
        t.ID_DceSoulPieceList = 1277,
        t.ID_DceGetTaskReward = 1278,
        t.ID_DceTaskRewardData = 1279,
        t.ID_DceExchangeCaptainCount = 1280,
        t.ID_DcePlotCopyWarBattleInfo = 1281,
        t.ID_DcePlotCopyWarEnter = 1282,
        t.ID_DcePlotCopyWarMove = 1283,
        t.ID_DcePlotCopyWarRollStep = 1284,
        t.ID_DceActivateTalent = 1285,
        t.ID_DceTalentList = 1286,
        t.ID_DceUpgradeTalent = 1287,
        t.ID_DcePlotCopyWarOpen = 1288,
        t.ID_DceAutoUpgradeScience = 1289,
        t.ID_DceGlobalArenaBack = 1290,
        t.ID_DceGlobalArenaBattle = 1291,
        t.ID_DceGlobalArenaBattleProgress = 1292,
        t.ID_DceGlobalArenaData = 1293,
        t.ID_DceGlobalArenaEncourage = 1294,
        t.ID_DceGlobalArenaPlayOffList = 1295,
        t.ID_DceGlobalArenaProstrate = 1296,
        t.ID_DceGlobalArenaSelfInfo = 1297,
        t.ID_DceGlobalArenaUpdateTactic = 1298,
        t.ID_DceSignUpAudition = 1299,
        t.ID_DceSalute = 1300,
        t.ID_DceSaluteData = 1301,
        t.ID_DceGoldLeaderExplore = 1302,
        t.ID_DceGoldLeaderGetOrder = 1303,
        t.ID_DceGoldLeaderInfo = 1304,
        t.ID_DceGoldLeaderBuyOrder = 1305,
        t.ID_DceLuckyGodBuyItem = 1306,
        t.ID_DceMonthCardData = 1307,
        t.ID_DceGlobalArenaChamption = 1308,
        t.ID_DceAutoEquipSeikoSoldier = 1309,
        t.ID_DceComposeSeiko = 1310,
        t.ID_DceDecomposeSeiko = 1311,
        t.ID_DceEquipSeiko = 1312,
        t.ID_DceForgeSeiko = 1313,
        t.ID_DceReductionSeiko = 1314,
        t.ID_DceReductionSeikoInfo = 1315,
        t.ID_DceRemouldSeiko = 1316,
        t.ID_DceSeikoList = 1317,
        t.ID_DceSeikoPieceList = 1318,
        t.ID_DceUnEquipSeiko = 1319,
        t.ID_DceUpgradeSeiko = 1320,
        t.ID_DceSaveForge = 1321,
        t.ID_DceEnterStageTower = 1322,
        t.ID_DceSetTacticForStageTower = 1323,
        t.ID_DceGetTacticForStageTower = 1324,
        t.ID_DceUpdateEnemyForStageTower = 1325,
        t.ID_DceStageTowerPurchaseAndResurr = 1326,
        t.ID_DceFindEnemyForStageTower = 1327,
        t.ID_DceSeikoShopData = 1328,
        t.ID_DceSeikoShopHandle = 1329,
        t.ID_DceOnearmedBanditTen = 1330,
        t.ID_DcePaperLockOperation = 1331,
        t.ID_DceShipLockOperation = 1332,
        t.ID_DceCaptainLockOpt = 1333,
        t.ID_DceRenameGuild = 1334,
        t.ID_DceSeikoLockOpt = 1335,
        t.ID_DceSoulLockOpt = 1336,
        t.ID_DcePartsLockOpt = 1337,
        t.ID_DceGoldIslandCancelHelped = 1338,
        t.ID_DceGlobalArenaCheckEncourage = 1339,
        t.ID_DceGuildBattleAuto = 1340,
        t.ID_DceTuanGouOpt = 1341,
        t.ID_DceStageTowerAcityData = 1342,
        t.ID_DceStageTowerAcityHandle = 1343,
        t.ID_DceSeiKoExchange = 1344,
        t.ID_DceSeiKoScore = 1345,
        t.ID_DceWeal = 1346,
        t.ID_DceRechargeBackGift = 1347,
        t.ID_DceRechargeBackGiftEnter = 1348,
        t.ID_DceCenterCampBattleCampRank = 1349,
        t.ID_DceUseSoulGift = 1350,
        t.ID_DceAutoEquipSoul = 1351,
        t.ID_DceUnAutoEquipSoul = 1352,
        t.ID_DceGlobalGuildBattleSign = 1353,
        t.ID_DceGlobalGuildBattleAdjust = 1354,
        t.ID_DceGlobalGuildBattleEncourage = 1355,
        t.ID_DceGlobalGuildBattleUpdate = 1356,
        t.ID_DceGlobalGuildBattleData = 1357,
        t.ID_DceGlobalGuildBattleSeeMember = 1358,
        t.ID_DceGlobalGuildBattleProstrate = 1359,
        t.ID_DceGlobalGuildBattleGuildGroupVs = 1360,
        t.ID_DceGlobalGuildBattleGuildVs = 1361,
        t.ID_DceGlobalGuildBattleVsBattle = 1362,
        t.ID_DceScoutGuild = 1363,
        t.ID_DceGlobalGuildBattleChamptionMember = 1364,
        t.ID_DceGlobalGuildBattleChamptionList = 1365,
        t.ID_DceActivityWebData = 1366,
        t.ID_DceGuideSave = 1367,
        t.ID_DceFocusAward = 1368,
        t.ID_DceExchangeCode = 1369,
        t
}();
